### ISSUE TITLE
Feature Request: PROXY support for RDP connections

### ISSUE THREAD

**Issue by Jonnyan404** [1Remote/PRemoteM#105]
**Is your feature request related to a problem? Please describe.**
国外的一些机器,大部分时间访问很慢,如果可以通过代理来加速,则会很快!

**Comment by VShawn** [comment]
RDP 本身不支持 Proxy，我也从来没试过 RDP via Proxy，因此需要花点时间去研究如何实现。

reference: https://github.com/mRemoteNG/mRemoteNG/issues/420

**Comment by zhucaidan** [comment]
MultiDesk 支持socks5 代理，或者用netch来代理主程序达到效果
