### ISSUE TITLE
Global and/or connection configuration option to lock window

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#120]
**Is your enhancement related to a problem? Please describe.**
Currently we have lock icon, but it needs to be manually clicked each time.

**Describe the solution you'd like**
I would like to have global and/or connection option to lock window. Global affects all connections and is used by default if nothing is specified on connection.

**Comment by majkinetor** [comment]
Argh, I still close the window all the time because I forget to lock it each time I open it. Then I reopen and immediately lock...

I think most people will forget to do this.

**Comment by VShawn** [comment]
move the close button of tab window to the right side (like mac app) may help. 

But it looks strange on the Windows platform.

![image](https://user-images.githubusercontent.com/10143738/128875924-fa4f6923-599e-4dff-96ba-f36ad2ed5d9b.png)

**Comment by majkinetor** [comment]
Position is not the problem but the fact that you need to set it up EACH time.

**Comment by VShawn** [comment]
I dont think so, if we move close button to the left side of the tab window, then, when we click the close button in RDP, the button in the RPD is on the right side, you will never hit the wrong button

**Comment by majkinetor** [comment]
Yeah, that could actually help.

**Comment by VShawn** [comment]
Oh, close button on the left side looks awful...  I tested it 1 second and give up this change....

**Comment by VShawn** [comment]
> Oh, close button on the left side looks awful... I tested it 1 second and give up this change....

Now I am trying to add a confirmation popup to the close button.

**Comment by majkinetor** [comment]
What happened to lock icon in latest version, remind me :)

**Comment by VShawn** [comment]
I think we dont need that button anymore since we have a closing confirm.

![image](https://user-images.githubusercontent.com/10143738/161874691-9612febb-0c3c-446a-8e69-5b6aa43950f8.png)

**Comment by majkinetor** [comment]
Didn't see that. 👍
