### ISSUE TITLE
Retire the old VncSharp and find an alternative

### ISSUE THREAD

**Issue by VShawn** [1Remote/PRemoteM#191]
In short, VncSharp may crashed and make PRemoteM crash.

**Since the repository of VncSharp was archived for 4 years**, I don't intend to make a PR to fix this. It's time to retire the old VncSharp and find an alternative. (Or maybe we can leave a blank default runner for vnc, and ask user select a runner then first time start the vnc session)

some alternatives:
https://github.com/quamotion/remoteviewing
https://github.com/MarcusWichelmann/MarcusW.VncClient

_Originally posted by @VShawn in https://github.com/VShawn/PRemoteM/issues/190#issuecomment-1020872844_

**Comment by majkinetor** [comment]
Check this out: https://github.com/mRemoteNG/VncSharpCore

**Comment by VShawn** [comment]
tried [mRemoteNG/VncSharpCore](https://github.com/mRemoteNG/VncSharpCore) can not work directly
