### ISSUE TITLE
Select protocol runner per connection

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#205]
**Is your enhancement related to a problem? Please describe.**
Currently it seems like you need to set default protocol runner in order for connection to work with it. It would be better if we are allowed to select protocol per connection.

**Describe the solution you'd like**
Add a combo box with protocol selection on those protocols that have multiple runners.

**Describe alternatives you've considered**
No alternative

**Comment by VShawn** [comment]
sounds reasonable

**Comment by majkinetor** [comment]
Missing translation:

![image](https://user-images.githubusercontent.com/85767/170027742-acde2217-ac56-47b3-9ee2-ec03a8dee86b.png)
