### ISSUE TITLE
Exception when clicking the info button on RDP connect bar on Windows 11

### ISSUE THREAD

**Issue by AnalogKnight** [1Remote/PRemoteM#208]
问题描述： 使用RDP连接远程主机时，如果在全屏状态下，点击上方标题栏的"连接信息"按钮，应用程序会停止响应，数秒后意外关闭。系统环境： Windows 11 22563.1 目前尚未在Windows 10下进行测试。

**Comment by AnalogKnight** [comment]
“连接信息”按钮为图中上方标题栏图钉状按钮右侧的按钮。

**Comment by VShawn** [comment]
很奇怪，我之前还尝试过看如何才能把`连接信息`调出来呢

在我的win10上，通过 PRemoteM 打开RDP这个按钮一直是不存在的。

![image](https://user-images.githubusercontent.com/10143738/155864070-94021405-6af4-4bad-95fd-98214d9ea3f5.png)

我现在没有 Win11 的环境，等有空了整台 Win11 设备再来测试。

**Comment by AnalogKnight** [comment]
感谢您的回复。我将在Windows 10上测试一下看看是否有相同的问题。

**Comment by AnalogKnight** [comment]
> 很奇怪，我之前还尝试过看如何才能把`连接信息`调出来呢
> 
> 在我的win10上，通过 PRemoteM 打开RDP这个按钮一直是不存在的。
> 
> ![image](https://user-images.githubusercontent.com/10143738/155864070-94021405-6af4-4bad-95fd-98214d9ea3f5.png)
> 
> 我现在没有 Win11 的环境，等有空了整台 Win11 设备再来测试。

您好，我刚才在Windows 10下的设备进行了测试，该按钮正常显示，并且点击后正常显示了连接状态，应用程序没有异常退出。

**Comment by VShawn** [comment]
感谢你的测试，看来确实是 Win11 的专属 bug
