### ISSUE TITLE
New application name

### ISSUE THREAD

**Issue by VShawn** [1Remote/PRemoteM#214]
Since
1. Someone found the name is ambiguous by [Pre-motem](https://en.wikipedia.org/wiki/Pre-mortem)
2. Someone reminded me that the current name is hard to remember #203 

But I don't have any naming inspiration.

**Comment by majkinetor** [comment]
Its also similar 'pre-mortem' which means before dead or something :)
Also, word 'personal' is less and less true .

**Comment by majkinetor** [comment]
> But I don't have any naming inspiration.

Lets keep this open and add list of names in the description over some longer time period.

**Comment by VShawn** [comment]
maybe simply
- Remote Control
- Remote Gear
- Remote Machine

:face_with_spiral_eyes:

**Comment by majkinetor** [comment]
Doesn't look searchable :) One aspect of naming things, if one asks google for remote control you are definitely not going to be among first zillion pages. The same for 'remote machine', but 'remote gear' is not typical.

**Comment by VShawn** [comment]
Haha, I didn't consider search engines at all.

`Remote gear`  reminds me of the video game [Gears](https://www.gears5.com/) : )

Then, Let use it as the first choice.

**Comment by VShawn** [comment]
I think of `Remote Greas` 
plural emphasis on a variety of remote protocols

**Comment by majkinetor** [comment]
1RM
One Remote Manager to Rule Them All :)

**Comment by VShawn** [comment]
> 1RM or 1RAM
> 
> One Remote (Access) Manager to Rule Them All :)
> 
> 
> 
> 1RAM is more pronounceable and easy on tongue. Both are not used at all (there is [1RM](https://en.wikipedia.org/wiki/One-repetition_maximum) in weight training though)

the fullname is acceptable, while the abbreviation is too hard core for a man who is never know this app(can not read this app is built for remote control from the name'1RAM').

'One Remote Manager' is easy to understand but maybe it's too long for a app`s name.

Or what do you think of 'OneRemote'?

And these similar names:

PiRemote
ProRemote
InRemote （In stands for integrate）


Anyway it's time to make a decision since net6 version is about to complete

**Comment by majkinetor** [comment]
I like OneRemote although there are competimg names in remote controler space. But ok... we have to choose something... and 1RM still applies :)

**Comment by majkinetor** [comment]
Based on internal discussion we settled currently on:

- OneRemote 
One Remote Access Manager to Rule Them All 
Shortcut: 1RAM 

Shell we close this ticket @VShawn or let it live ?

**Comment by VShawn** [comment]
I will open a new ticket for the transfer

**Comment by majkinetor** [comment]
Maybe we could also shorten it to 1Remote ?

**Comment by VShawn** [comment]
Both are OK

1Remote is used by https://www.indiegogo.com/projects/1remote-a-single-remote-to-control-all-your-electronics-simply#/

**Comment by majkinetor** [comment]
That really looks like something irrelevant :) 

Also, notice that was the name of the campaign and 
> THIS CAMPAIGN IS CLOSED

**Comment by majkinetor** [comment]
Reopening this until the executable name and UI is actually changed.

**Comment by VShawn** [comment]
executable name will be `1Remote.exe` with the next update.

**Comment by majkinetor** [comment]
There is actually another ticket for this #238
