### ISSUE TITLE
Integrate FreeRDP

### ISSUE THREAD

**Issue by dethknite** [1Remote/PRemoteM#239]
I would highly recommend integrating wfreerdp instead of the deprecated activex rdp and mstscax. wfreerdp is up-to-date with security negotiation and has much more interoperability with RDP servers. There is even a recent nuget package that wraps up pretty much everything for consuming it.

https://www.nuget.org/packages/RoyalApps.Community.FreeRdp.WinForms/1.0.0#show-readme-container

I might try to port it into a fork.. but wpf is not really my strong suit... so we will see how far I get.

**Comment by majkinetor** [comment]
I tested this up and it could be used now if you set up protocol. You have to do it via VNC protocol

![image](https://user-images.githubusercontent.com/85767/168690147-5be60d5b-8c66-4a15-abc0-ed662aee6bcd.png)

Set it as default VNC:
![image](https://user-images.githubusercontent.com/85767/168690211-9ef27f98-bd21-4088-921f-43f9e9857664.png)

Now create VNC connection. It works. Maybe a bit awkward...

**Comment by dethknite** [comment]
Never thought of that.. great idea. Thanks for sharing  👍🏻

**Comment by dethknite** [comment]
Yeah.. wfreerdp is what I ended up porting my project to because the mstscax stuff just got so buggy from lagging behind. It has great support out of the box, including drive mapping xfreerdp /v:rdp.contoso.com /drives, and the cross platform is definitely a perk.

**Comment by VShawn** [comment]
some doubts:

- can wfreerdp support multi-screen? (this is my main motivity of this repository)
- can it support resize rdp window on fly?
- can it support HiDPI, and multi-screen with different Dpi?

**Comment by dethknite** [comment]
Yes and yes.. I use it as a replacement for rdp on non Win OS's. It really depends on how you want to utilize it, and what you wish to do with it.

:Full screen example
`/v:{host} /port:{port} /u:{user} /d:{domain} /p:{pass} /f /bpp:32 /cert-ignore /workarea +clipboard`

:Dynamic Resolution
`/v:{host} /port:{port} /u:{user} /d:{domain} /p:{pass} /dynamic-resolution /bpp:32 /cert-ignore /workarea +clipboard`

:HiDPI and DPI scaling
`/v:{host} /port:{port} /u:{user} /d:{domain} /p:{pass} /w:1280 /h:920 /smart-sizing /bpp:32 /cert-ignore /workarea +clipboard`

Etc.. etc.. you get the picture

**Comment by majkinetor** [comment]
Thanks @dethknite for your input, very valuable.

I tested an hour yesterday and it doesn't seem to be any worst then RDP, with identical settings I couldn't spot the difference.

**Comment by VShawn** [comment]
I wonder if we can make a new PRemoteM app that work with external tools only. 

The tab windows and internal runners will be removed. The new app will act as a session password manager and the launcher of KiTTY \ FreeRDP \ MSTSC \ WinSCP \ TightVNC. 


---

BTW, I tested the [FreeRDP control](https://www.nuget.org/packages/RoyalApps.Community.FreeRdp.WinForms/1.0.0#show-readme-container), this wraper does not achieve all the functionality of FreeRdp.

**Comment by majkinetor** [comment]
Lets talk about that in new ticket that I will open soon. Or better, lets enable discussions here.

**Comment by VShawn** [comment]
>  lets enable discussions here.

sure
