### ISSUE TITLE
单独维护账号密码

### ISSUE THREAD

**Issue by Kerwin1202** [1Remote/PRemoteM#242]
另外不知道是否会考虑单独维护一套账号，毕竟很多服务器可能账号密码都是一样的 (虽然不安全，但是对于公司局域网似乎无所谓)，这样每次新加机器就不用重新输入一遍，像 ios 上的 `microsoft rd client` 软件

![image](https://user-images.githubusercontent.com/16319833/170226275-e9c618aa-fdc1-47bc-ba2d-6e148818790e.png)

**Comment by VShawn** [comment]
不准备开发这套功能，因为 #83 已经开发了批量编辑功能，通过批量编辑就能够统一设置多个服务器的账号密码了。

而如果支持这个功能，现有的数据模型、界面逻辑、导入、导出功能都要改，太麻烦了。
