### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by fkue587** [1Remote/PRemoteM#247]
1.增加挪动服务器 上移或下移 
2.多开  标签页不能同等距离 如果名字长了就把短的盖住了
3.增加不生成日志选项
4.新添加的配置增加一个全局修改要不然每次添加都要修改一次
5.增加框选列表

---

1. Add server list oder arrange manually
2. Multiple tabs cannot be at the same distance. If the name is long, the short one be covered
3. Add the option to not generate logs
4. Add a global modification to the newly added configuration, or you must modify it every time you add it
5. Add frame selection list

**Comment by VShawn** [comment]
1. 这个需求可以做到，但个人认为意义不大，而且会和我之后的多数据源模式的规划冲突。我会考虑一下，不过真要做也是优先级非常低的，近期内我没有精力去实现它。
2. 标签页本身就不是等距离的，应该是你的服务器名字太长了，超过了最大长度限制。下图，华为云短，阿里云长，当然也许可以添加一个允许设置 tab 宽度的选项。
![image](https://user-images.githubusercontent.com/10143738/170847577-d1980f02-e5d1-45c5-92d1-f2a14eb671aa.png)
3. 这个建议不会被采纳，任何软件都需要日志。现在的日志为调试方便，打开了所有 debug level 的信息，当软件最终稳定下来后，会改为只记录 info 等级以上的信息，但依然不会允许不生成日志。
4. 类似的问题我们讨论过，并认为在有了 duplicate 和 buck edit 的当前，默认配置并不是非常必要。 https://github.com/1Remote/PRemoteM/issues/128,  https://github.com/1Remote/PRemoteM/issues/73 ，
5. 框选可以做，这种涉及改用户界面交互的工作我做的很慢，所以估计要等很久才能见到哈。

---

1. This requirement can be achieved, but I personally think it is of little significance, and it will conflict with my future multi-data source model planning.
2.  The tab headers are not in a same distance now, may be that your server name is too long. Of course maybe we can offing an option that allows setting the tab header width.
3. This suggestion will not be adopted, WE DID NEED LOG. The current version APP logging all of the debuglevel information . When the software is finally stabilized, it will be changed to only record information above the info level, but it is still not allowed to disable the logs.
4. Similar issues have been discussed, and we believe that with duplicate and buck edit, the default configuration is not very necessary.
