### ISSUE TITLE
.NET 6.x : To run this application, you must install missing framework => loop asks again and again to install .NET

### ISSUE THREAD

**Issue by accnetdev** [1Remote/PRemoteM#252]
PRemoteM.0.7.0.alpha2.x64 : it does not launch even if .NET (x86 or x64) is installed.
Same bug like the one I have with the nightly build of MremoteNG that require .NET 6.x.

Windows 10 or Windows 2019 server.

**Comment by accnetdev** [comment]
Fixed : download and install the SDK ( dotnet-sdk-6.0.300-win-x64.exe ) not only the runtime as asked ( dotnet-runtime-6.0.5-win-x64.exe ).

**Comment by majkinetor** [comment]
Why would it need SDK, if so, that is some bug.

**Comment by accnetdev** [comment]
In fact, it seems to require the desktop version of the runtime, that is included in the SDK.
Man can only install the desktop runtime. My initial error was to install the console version of the runtime.
Personally, I am OK to install the SDK which could be useful for many other things.
Have a good day.

**Comment by majkinetor** [comment]
Yes, desktop version is required.
