### ISSUE TITLE
RDP协议下固定分辨率时自定义缩放比例不起作用

### ISSUE THREAD

**Issue by syazyz** [1Remote/PRemoteM#253]
**Describe the bug**
版本0.7.0-pre-release-2
系统Win10 LTSC 21H2，RDP连接远程主机Windows Server 2022，在设置里选择自定义分辨率（固定），缩放选择定制
连接后分辨率正常，但缩放未起效

**To Reproduce**
见截图

**Expected behavior**
见截图

**Screenshots**
![1](https://user-images.githubusercontent.com/11090567/171962614-b73d37f3-f9e6-405f-bec3-e9bbfd3ddb99.png)
![2](https://user-images.githubusercontent.com/11090567/171962700-2c895fae-8581-428c-935e-bcc667e5d335.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10 LTSC 21H2]
 - PRemoteM Version [0.7.0-pre-release-2]

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/172740184-fc581f14-d00a-40d2-8e1c-4fc28f0b1a65.png)


自测没有复现这个bug，可能和系统有关。或者你本身是使用2k或4k的显示器并且设置了缩放么？如果你的系统设置了150%的缩放，软件里再设150缩放，就等于100%缩放。

**Comment by syazyz** [comment]
感谢回复。我确实是正在用4k显示器，但这与系统全局缩放应该没有太大关系，而是远程连接本身缩放的问题。现在我把系统全局缩放改成100%，然后再改变配置文件中的缩放依旧没有变化，与前述情况相同。

**Comment by VShawn** [comment]
很遗憾，可能我暂时无法解决你遇到的问题。可能需要把  MSTSC 客户端从微软 AxMSTSC 客户端迁移到 FreeRDP 来解决这些坑问题。AxMSTSC 经常在不同系统中遇到 bug。
