### ISSUE TITLE
mstsc模式设置高宽无效

### ISSUE THREAD

**Issue by yang5355** [1Remote/PRemoteM#256]
![image](https://user-images.githubusercontent.com/59274878/172809875-a28294e0-2562-4841-81ee-350328b1eaee.png)

![image](https://user-images.githubusercontent.com/59274878/172809970-e0660e7e-90b9-4cb9-bba1-39339a2c7e1e.png)

如题这样设置还是全屏连接，不能按设置的分辩率显示，我的显示器是1080，放大125%

**Comment by VShawn** [comment]
设置窗口分辨率的时候，不能启用全屏模式，所以你必须选择 

![image](https://user-images.githubusercontent.com/10143738/172848139-3eca8178-c9a6-4807-8efe-8ec0def7ae12.png)

**Comment by yang5355** [comment]
nice
