### ISSUE TITLE
能否为列表页面添加一个分组显示

### ISSUE THREAD

**Issue by yang5355** [1Remote/PRemoteM#258]
场景：我管理几十个服务器，分别在不同机房，能否设置分组，一个机房为一个组，方便管理

**Comment by VShawn** [comment]
嗯？可以详细描述一下么，我不是很理解你的需求。感觉现有的 tag 系统已经可以满足你的需求了。

比如说像这样：

![image](https://user-images.githubusercontent.com/10143738/173297071-8502c9f0-31a3-4048-9d0c-abf303e97cd8.png)

**Comment by yang5355** [comment]
哦，看到了，是我不会用，没发现这么好的标签功能，赞

**Comment by VShawn** [comment]
另外这个标签系统支持筛选功能，下图表示筛选出 `Work` 标签内所有非 `Ali云` 的 `RDP` 服务器。感觉你那么多服务器，应该用的上这个功能。

![image](https://user-images.githubusercontent.com/10143738/173299893-d213a485-9f43-401c-8d15-5b2aece01918.png)
