### ISSUE TITLE
mstsc模式不指定宽高的话能否自动计算当前窗口最大化而不是全屏

### ISSUE THREAD

**Issue by yang5355** [1Remote/PRemoteM#259]
![Snipaste_2022-06-17_18-03-42](https://user-images.githubusercontent.com/59274878/174278355-db5b4435-7b33-4a94-94bc-33a18c71f988.png)

![image](https://user-images.githubusercontent.com/59274878/174279304-7ac09888-ae50-4dff-ae8a-59218ec1afc2.png)

我分辨率是1920 * 1080，然后我使用mstsc模式不指定宽高的话就默认是全屏，如截图我经常打开好多个远程桌面所以全屏不方便。
我需要为每个远程都指定宽高（1920 * 990）,因为截止到状态栏的高度是990，再多就出现滚动条了，数据是本机测试。

建议：能否像winform一样自动计算宽高，也就是最大化，而不是全屏

PS：因为我电脑有外接显示器，缩放不一样，所以用mstsc的体验比较好

谢谢！

**Comment by VShawn** [comment]
抱歉，MSTSC 模式的目的仅仅是为了添加一些可自定义选项，我不打算为它添加更多更复杂的功能了。再加功能我一个人维护不过来，现在每次新版本测试的时候都已经出现了某些冷门功能我忘记去测的情况了。

针对你的问题，你这样设置应该就行了，不需要手动输入参数。

![image](https://user-images.githubusercontent.com/10143738/174286163-fb57a161-081f-41d5-97f4-4d2d9e077ed1.png)


另外我自己在家用 200% + 150% 的双4k显示器，用 Tab 窗体打开 RDP 的体验感觉还挺好的，在你那是遇到了什么问题么？

**Comment by VShawn** [comment]
I will close this since we get no response
