### ISSUE TITLE
增加批量检测

### ISSUE THREAD

**Issue by fkue587** [1Remote/PRemoteM#260]
增加批量检测是否可用 这样如果服务器多了过期了  一个一个试太麻烦了.
添加一个保存为默认配置 很多服务器这样我可以直接更改IP就行了 分辨率我就不用一个一个调整了.. 
添加   全部页的IP后面添加 创建时间和最后使用时间

**Comment by VShawn** [comment]
> 增加批量检测是否可用

我认为这个功能可以但没必要，我设计这个工具是为了管理10台左右内网服务器用的，我认为服务器存活检测越过了APP的设计边界了。不过话说回来，我不清楚云服务器到期该怎么检测，莫非直接PING一下么。如果只是PING一下，应该很多外部工具就可以做到，或许我可以添加一个接口，来调用外部工具PING一遍所有的服务器。

> 添加一个保存为默认配置 很多服务器这样我可以直接更改IP就行了
 
这个你直接在服务器列表里多选，然后点编辑，就可以批量修改IP了。

> 添加 全部页的IP后面添加 创建时间和最后使用时间

目前没有存这个信息，0.8 版本以后可能会添加。
