### ISSUE TITLE
125%缩放画面会有点模糊

### ISSUE THREAD

**Issue by zhj9709** [1Remote/PRemoteM#261]
笔记本14英寸，1080p分辨率，缩放125%。使用PRemoteM远程画面会比系统自带的mstsc远程画面模糊一点。
软件本身显示也会模糊一点。

可能是Windows缩放的锅，但希望可以再优化一下。

**Comment by VShawn** [comment]
可以给个截图看看MSTSC和PRemoteM对比效果么? 不过这一块似乎没有留有清晰度设置接口，我看你无法改进这个，要不你把桌面体验设置为高试试？

![image](https://user-images.githubusercontent.com/10143738/174692265-d30b8664-6f2b-4d15-bb63-6238c861f078.png)

**Comment by zhj9709** [comment]
> 可以给个截图看看MSTSC和PRemoteM对比效果么? 不过这一块似乎没有留有清晰度设置接口，我看你无法改进这个，要不你把桌面体验设置为高试试？
> 
> ![image](https://github.com/assets/10143738/d30b8664-6f2b-4d15-bb63-6238c861f078)

昨天是想上传图片的，但公司的网络不允许上传。
这里的模糊应该是软件没有适配好125%的缩放。就算不连远程桌面，软件本身显示在125%的缩放下也比100%缩放模糊。

**Comment by zhj9709** [comment]
> 可以给个截图看看MSTSC和PRemoteM对比效果么? 不过这一块似乎没有留有清晰度设置接口，我看你无法改进这个，要不你把桌面体验设置为高试试？
> 
> ![image](https://github.com/assets/10143738/d30b8664-6f2b-4d15-bb63-6238c861f078)

100%缩放
![100](https://user-images.githubusercontent.com/13991774/174795114-468e5817-76e9-447c-93d6-1f550c23e909.png)

125%缩放
![125](https://user-images.githubusercontent.com/13991774/174795166-2f2a1f4f-793b-4524-b636-54d772473245.png)

**Comment by VShawn** [comment]
您说的程序本身界面的模块的模糊确实存在，但事实上在 HiDPI 适配上我没有做任何工作，一切都是由微软的WPF框架自己处理的，我所作的仅仅是确保 WPF  的 per Monitor DPI aware 特性处于启用状态。

然后我去搜索了一圈都没有找到 125% 分辨率下模糊的解决方案，倒是有解释说 125% 缩放下像素无法被整除，所以会模糊。

**Comment by VShawn** [comment]
捣鼓了一通，没有任何改善。不修了 😢
