### ISSUE TITLE
could not open a SFTP by private key.

### ISSUE THREAD

**Issue by wolvth** [1Remote/PRemoteM#262]
win11，store版本，桌面版本
ssh导入openssh格式的key登录不了。
转换成ppk可以登录，但是sftp依旧验证不通过

**Comment by VShawn** [comment]
1. SSH 使用的是 KiTTY，KiTTY 不支持 openssh key，必须先转到 ppk 才能用，除非 KiTTY 项目进行了改进，否则我没办法支持 openssh key.
2. SFTP 是直接打开一个 SFTP，还是从 SSH 中选择“同时打开SFTP”选项？SFTP 的密钥登录我很久没测试过了（因为SSH SFTP[都是我自己的服务器，全都用账号密码登录，懒得设置私钥），可能在某次改版后失效。

![image](https://user-images.githubusercontent.com/10143738/174692038-c9fc8e5b-9efc-4824-a128-789a5a7bfcfd.png)

**Comment by wolvth** [comment]
直接打开，SSH选择同时打开都不行。调用winscp也验证失败。独立使用winscp没问题。

**Comment by VShawn** [comment]
`sftp://%PRM_USERNAME%@%PRM_HOSTNAME%:%PRM_PORT% /privatekey=%PRM_SSH_PRIVATE_KEY_PATH%`

参数测试通过

**Comment by VShawn** [comment]
问题已修复。

经查内置的 SFTP 客户端基于 SSH.NET 开发，它仅支持 OpenSSH key，所以致使本软件的 SFTP via privacy key 失效。先问题修复后，软件内置 SSH 仅支持 PUTTY key，内置的 SFTP 仅支持 OpenSSH key，体验相当奇怪。经测试 发现，WinSCP 支持 Putty OpenSSH 两种格式的私钥，因此推荐使用 WinSCP 作为 SFTP 客户端。
