### ISSUE TITLE
0.7版本后第二次打开 RDP 会回报 4360 错误

### ISSUE THREAD

**Issue by leezm** [1Remote/PRemoteM#263]
**Describe the bug**
我从微软商店升级到的0.7，双击winserver2016就闪两下自动关了远程窗口，程序未闪退
**To Reproduce**
1. 找台winserver2016的机器
2. 双击远程

**Expected behavior**
我也不知道是不是发生了什么错误，升级前上个版本是好的
**Screenshots**
就闪两下自动关闭新窗口了
**Desktop (please complete the following information):**
 - OS: win11
 - PRemoteM Version [e.g. 0.4.6.20071234]
微软商店版0.7
**Additional context**

**Comment by leezm** [comment]
刚升级了微软最新的7月补丁，然后重启过后好了...不知道是重启好的还是打补丁好的...

**Comment by VShawn** [comment]
自测 Win10 下用商店版本远程到2016没问题。

![image](https://user-images.githubusercontent.com/10143738/178628453-8cddc6e4-2d16-49f9-9b3b-a82f8197e124.png)

我注意到你那边是 win11, 所以我用 win11 的虚拟机也进行了测试，依然没有问题。

![image](https://user-images.githubusercontent.com/10143738/178628909-6f2c4c2a-4d60-4907-83c6-6d9dbda0f943.png)

所以目前无法定位到底发生了什么。

你可以帮忙确认一下日志中发生了什么？复现一下这个bug后把日志po上来即可。

**Comment by yujianjian1013** [comment]
我这边还是有这个问题，最近比较常用的几个远程桌面都会连不上，连上会直接黑屏并自动关闭窗口 @VShawn

**Comment by leezm** [comment]
> 我这边还是有这个问题，最近比较常用的几个远程桌面都会连不上，连上会直接黑屏并自动关闭窗口 @VShawn 

我后来又发现这个问题了，包括远程一台win10电脑，重开软件不一定有用，又懒得重启电脑了…

**Comment by yujianjian1013** [comment]
> 

重启软件和重启电脑都是没用的，我现在只能用windows自带的了

**Comment by leezm** [comment]
> > 
> 
> 重启软件和重启电脑都是没用的，我现在只能用windows自带的了

这个issue关闭了，作者换看得见吗...

**Comment by yujianjian1013** [comment]
> > > 
> > 
> > 
> > 重启软件和重启电脑都是没用的，我现在只能用windows自带的了
> 
> 这个issue关闭了，作者换看得见吗...

不知道诶，我@他了，不行我待会再开一个

**Comment by yujianjian1013** [comment]
> 看得见的，你们都是 error code 4360 么？
> 
> > 重启软件和重启电脑都是没用的，我现在只能用windows自带的了
> 
> 然后 MSTSC 可以打开远程桌面，但用软件就无法连上是么？

是的，软件会直接黑屏，然后立马闪退掉

**Comment by VShawn** [comment]
> @VShawn 你可以看下这个视频，视频刚好超了10M一点点，我压缩放上来 [QQ录屏20220718175145.zip](https://github.com/1Remote/PRemoteM/files/9131028/QQ.20220718175145.zip)

从视频上看，和 @ndd200 反馈的情况并不一样，但感觉你视频中的情况更加诡异，明明已经连接成功进入登录流程了又直接短线...不知道是不是商店版本对联网权限进行了控制。

能否帮忙测试一下 exe 版本是否有这个问题？

**Comment by yujianjian1013** [comment]
> > @VShawn 你可以看下这个视频，视频刚好超了10M一点点，我压缩放上来 [QQ录屏20220718175145.zip](https://github.com/1Remote/PRemoteM/files/9131028/QQ.20220718175145.zip)
> 
> 从视频上看，和 @ndd200 反馈的情况并不一样，但感觉你视频中的情况更加诡异，明明已经连接成功进入登录流程了又直接短线...不知道是不是商店版本对联网权限进行了控制。
> 
> 能否帮忙测试一下 exe 版本是否有这个问题？

github不会用，怎么下载EXE版啊

**Comment by leezm** [comment]
> ```
> 
> 我有同样的问题。
> 于是我装了Github版便携模式，商店版配置存appdata。两个版本用同一个PRemoteM.db。对比两边的json配置，几乎是一样的，但是商店版打开某几个远程就是看着像连上了，在调整分辨率的时候闪退了，重启程序也无法解决。
> 本来还想仔细研究的，在反复重启的过程中，两个版本又都不闪退了。
> 
> ———————割一下———————
> 现在大致可以确认，有问题的是商店版。
> 商店版连接某几台服务器时候，会闪一下退出连接。同一时间，关商店版，启动Git版没问题。然后再关Git版，启动商店版就闪退。
> 两个版本的Locality.json和PRemoteM.json配置是一致的，尤其是分辨率完全一样。
> 
> 日志里错误都是error code 4360。
> 
> 
> [T:001][10:59:57.069]	`Debug`		RDP Host: RdpOnDisconnected
> [T:001][10:59:57.070]	`Debug`		AxMsRdpClient09Host: Status => Disconnected
> [T:001][10:59:57.071]	`Warning`		[AxMsRdpClient09Host.cs(OnRdpClientDisconnected:102)]	RDP(blablabla) exit with error code 4360(未能重新连接到远程会话。
> 请重新尝试连接。)
> [T:001][10:59:57.554]	`Debug`		RDP Host: _rdpClient.Dispose()
> [T:019][10:59:57.558]	`Debug`		MarkProtocolHostToClose: marking to close: AxMsRdpClient09Host(id = 40, hash = 13273752)
> [T:019][10:59:57.559]	`Debug`		Current: Host = 0, Full = 0, Tab = 1, HostToBeDispose = 1
> [T:019][10:59:57.562]	`Debug`		CloseEmptyWindows: closing tab(16355056)
> [T:019][10:59:57.563]	`Info`		CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 1, WindowToBeDispose = 1
> [T:019][10:59:57.563]	`Warning`		[SessionControlService.cs(<CloseProtocolHostAsync>b__0:535)]	CloseEmptyWindows: 1 Empty Host closed
> [T:019][10:59:57.565]	`Debug`		Closing: 1 Empty Host.
> [T:019][10:59:57.566]	`Info`		CloseMarkedProtocolHost: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0
> [T:001][10:59:57.595]	`Debug`		RDP Host: _rdpClient.Dispose()
> ```
> 
> _Originally posted by @ndd200 in [#213 (comment)](https://github.com/1Remote/PRemoteM/issues/213#issuecomment-1186715119)_
> 
> 请问 1.你们用的是商店版本还是 exe 版本？ 2.你们的远程桌面闪退后，日志中和这位老兄提供的信息是一样的么？

商店版，我也是错误4360

**Comment by leezm** [comment]
> 

@VShawn 我还要反应个问题，不知道是不是商店版的问题，我点log路径的定位到不会打开资源管理器，要自己复制路径手工去找...

**Comment by yujianjian1013** [comment]
> > 
> 
> @VShawn 我还要反应个问题，不知道是不是商店版的问题，我点log路径的定位到不会打开资源管理器，要自己复制路径手工去找...

我也有这个问题

**Comment by yujianjian1013** [comment]
[PRemoteM.log_20220718.md](https://github.com/1Remote/PRemoteM/files/9131150/PRemoteM.log_20220718.md)
这个是我今天商店版的日志

**Comment by yujianjian1013** [comment]
![image](https://user-images.githubusercontent.com/49021308/179491515-f68c5f21-6a87-4cc4-94f5-400942bc38f7.png)
exe版本提示要安装这个 @VShawn ，我安装后可以打开EXE版本，但是跟商店版有同样的问题，链接刚才视频里那个服务器时还是会闪退

**Comment by yujianjian1013** [comment]
我的EXE版本又不闪退了，就很奇怪。。。

**Comment by VShawn** [comment]
> @VShawn 我还要反应个问题，不知道是不是商店版的问题，我点log路径的定位到不会打开资源管理器，要自己复制路径手工去找...

@leezm  @yujianjian1013 这个是商店版的隔离特性，只有 APP 能访问自己的 APP_DATA 路径。

> 商店版，我也是错误4360
> 今天下午用Git版7.0，两种问题暂时都没碰到。

商店里的 app 受到各种限制，包括但不限于本地路径访问、执行权限、联网，所以我才怀疑是微软对商店 APP 的联网进行了限制。偏偏这些问题又非常难以 debug，每次修改上传以后都要审核一到两天才能发布，老实说我已经在考虑放弃商城版了。

**Comment by VShawn** [comment]
> 但是进入桌面改分辨率的时候，闪退
> TabWindowWidth/TabWindowHeight似乎能好

理论上这个值和打开远程连接没啥关系，我这里做的是调用`微软的远程桌面控件`输入账号密码然后登录，等登录完成后调整分辨率到 TabWindowWidth/TabWindowHeight。如果真是因为这个原因导致闪退而又没有错误日志，那么很有可能是`微软的远程桌面控件`发生了内部错误，老实说这个我可能修不好。

**Comment by VShawn** [comment]
> > > @VShawn 我还要反应个问题，不知道是不是商店版的问题，我点log路径的定位到不会打开资源管理器，要自己复制路径手工去找...
> > 
> > 
> > @leezm @yujianjian1013 这个是商店版的隔离特性，只有 APP 能访问自己的 APP_DATA 路径。
> > > 商店版，我也是错误4360
> > > 今天下午用Git版7.0，两种问题暂时都没碰到。
> > 
> > 
> > 商店里的 app 受到各种限制，包括但不限于本地路径访问、执行权限、联网，所以我才怀疑是微软对商店 APP 的联网进行了限制。偏偏这些问题又非常难以 debug，每次修改上传以后都要审核一到两天才能发布，老实说我已经在考虑放弃商城版了。
> 
> 但是商店版更新方便啊...

我之前弄商店版就是因为它方便，但是商店版总是会遇到各种莫名其妙的问题，心很累的。


@leezm @yujianjian1013 @ndd200

对了如果老是连接不上，其实还有一招，如图把这个选项勾上，APP 就会调用系统自带的远程桌面来连接。

![image](https://user-images.githubusercontent.com/10143738/179503302-eff8fb07-8e93-4034-9844-b53468ea6de5.png)

**Comment by VShawn** [comment]
error coce 4360 的含义我都找不到 😢 

![image](https://user-images.githubusercontent.com/10143738/179505037-3d0e9537-e1c4-46c3-8860-d467e72bb0a9.png)

**Comment by ndd200** [comment]
> error coce 4360 的含义我都找不到 😢
> 
> ![image](https://user-images.githubusercontent.com/10143738/179505037-3d0e9537-e1c4-46c3-8860-d467e72bb0a9.png)

我先用几天git版，如果一直没有问题……作为远程桌面的重度用户，只能放弃商店版了。

**Comment by yujianjian1013** [comment]
> > error coce 4360 的含义我都找不到 😢
> > ![image](https://user-images.githubusercontent.com/10143738/179505037-3d0e9537-e1c4-46c3-8860-d467e72bb0a9.png)
> 
> 我先用几天git版，如果一直没有问题……作为远程桌面的重度用户，只能放弃商店版了。

我也是，我还把git版发给朋友用了

**Comment by ndd200** [comment]
另外我说的，远程桌面套娃的情况下，TabWindowWidth/TabWindowHeight的值经常被改小，然后第一次打开远程连接，窗口会非常小，影响到远程服务器桌面的窗口。这个很不方便，能否加一个全局的配置项，默认下这两个值？

**Comment by VShawn** [comment]
> 我先用几天git版，如果一直没有问题……作为远程桌面的重度用户，只能放弃商店版了。

@leezm @yujianjian1013 我也快放弃了，昨晚上想更新一版测试一下，结果微软合作伙伴中心愣是登录不上。

> 另外我说的，远程桌面套娃的情况下，TabWindowWidth/TabWindowHeight的值经常被改小

@ndd200

可以描述一下什么是桌面套娃么？TabWindowWidth/TabWindowHeight的值会被改成多少？

这两个值是自动根据当前窗口大小设置的，拉大一点就变大，拉小一点就变小，理论上存的是你窗口最后一次改变大小后的值。

**Comment by ndd200** [comment]
> > 我先用几天git版，如果一直没有问题……作为远程桌面的重度用户，只能放弃商店版了。
> 
> @leezm @yujianjian1013 我也快放弃了，昨晚上想更新一版测试一下，结果微软合作伙伴中心愣是登录不上。
> 
> > 另外我说的，远程桌面套娃的情况下，TabWindowWidth/TabWindowHeight的值经常被改小
> 
> @ndd200
> 
> 可以描述一下什么是桌面套娃么？TabWindowWidth/TabWindowHeight的值会被改成多少？
> 
> 这两个值是自动根据当前窗口大小设置的，拉大一点就变大，拉小一点就变小，理论上存的是你窗口最后一次改变大小后的值。

设置：分辨率“适应窗口大小”，缩放“跟随系统”。
1.用2.8K屏的笔记本（2880*1800 DPI 200%）远程2K屏（2560*1440）的台式机，再通过台式机远程服务器。（远程窗口最大化，显示本地桌面的任务栏。）
2.把远程工具都关了。
3.回到2K屏的台式机，打开远程工具，去远程服务器。

这时候出现奇葩问题，因为程序默认保存前一次会话状态（而且用户都不知道前一次分辨率多大），第一次连接时的窗口会变得非常小（导致远程服务器当前打开的窗口都被缩小）。
这个锅是DPI 200%引发的吧，在2.8K屏上把一个窗口设置成某个大小，回到2K屏，窗口的大小是完全不一样的。具体怎样的分辨率我记不清了，我现在每次启动前覆盖一次Locality.json，把分辨率锁定在1680*1024。

**Comment by VShawn** [comment]
我平时就用 1k 笔记本全屏远程到一台开发机上，没试过套三层的，我改天借台 2k 笔记本重复一次你的操作试试。

**Comment by ndd200** [comment]
> 我平时就用 1k 笔记本全屏远程到一台开发机上，没试过套三层的，我改天借台 2k 笔记本重复一次你的操作试试。

我估计需要改DPI到150%或者200%才能复现，最近刚换了新笔记本，远程过后各种窗口大小都不对了。
本来和PRemoteM没关系，只是PRemoteM比较特别，第一次打开远程窗口不是最大化的，导致窗口尺寸过小。mRemoteNG的远程窗口，套在主界面里的，就不会有这个问题。

**Comment by leezm** [comment]
刚刚win11又推送了7月更新，重启后发现都能远程了，然后关掉再远程又不行了，这个第一次远程和后面的有什么区别呢...

**Comment by VShawn** [comment]
> 刚刚win11又推送了7月更新，重启后发现都能远程了，然后关掉再远程又不行了，这个第一次远程和后面的有什么区别呢...

我也想知道有什么区别😢，我对这个问题仍然完全没有头绪。

**Comment by VShawn** [comment]
found a same ticket here: https://forum.asg-rd.com/showthread.php?tid=11016

As this guy said

```
I'm sorry to hear that. Right now it's not clear what could cause those issues only on some installations. As my colleague stated we didn't change anything related to RDP in patch3. So first we need time to be able to reproduce the problem on our side and also this month is affected by vacation so things generally need a bit more time. If you extended your license then you will be able use the next patches as well.
```

I didn't change anything related to RDP in 0.7.0.

**Comment by VShawn** [comment]
0.7.1.1 准备更新，这个也许可以修复 `rdp error code 4360`

![image](https://user-images.githubusercontent.com/10143738/180588603-256f92f4-27da-4b3e-9ff5-78907a5dec24.png)

我用自己的测试组进行了测试，没有再出现无法打开远程桌面的情况了

![image](https://user-images.githubusercontent.com/10143738/180588714-25608548-096c-47f8-8384-6fbee497bbca.png)


等更新包审核通过后，需要麻烦各位帮忙测试一下这个问题是否真的被修复了，谢谢。

![image](https://user-images.githubusercontent.com/10143738/180588676-6e7b10c7-afeb-4124-ab41-8b1b1110a2ab.png)

**Comment by leezm** [comment]
> 0.7.1.1 准备更新，这个也许可以修复 `rdp error code 4360`
> 
> ![image](https://user-images.githubusercontent.com/10143738/180588603-256f92f4-27da-4b3e-9ff5-78907a5dec24.png)
> 
> 我用自己的测试组进行了测试，没有再出现无法打开远程桌面的情况了
> 
> ![image](https://user-images.githubusercontent.com/10143738/180588714-25608548-096c-47f8-8384-6fbee497bbca.png)
> 
> 等更新包审核通过后（最长要审核3天），需要麻烦各位帮忙测试一下这个问题是否真的被修复了，谢谢。
> 
> ![image](https://user-images.githubusercontent.com/10143738/180588676-6e7b10c7-afeb-4124-ab41-8b1b1110a2ab.png)

更新到商店最新版后，还是会4360，但是退出重新打开软件就行，第一次会成功，关闭在远程就不行，必须重启软件

**Comment by VShawn** [comment]
@leezm 由于周末微软放假，我提到的修复（0.7.1.1）还未被审核通过，现在商店上可下载的版本依旧是我修改前的。

**Comment by leezm** [comment]
> @leezm 由于周末微软放假，我提到的修复（0.7.1.1）还未被审核通过，现在商店上可下载的版本依旧是我修改前的，审核通过后我会在这里留言。
> 
> P.S. 微软商店过长的审核周期，也是让我想放弃维护商店版的一个重要原因。

更新了最最新版试了下可以了！感谢！微软商店更新方便啊~~

**Comment by ndd200** [comment]
> > @leezm 由于周末微软放假，我提到的修复（0.7.1.1）还未被审核通过，现在商店上可下载的版本依旧是我修改前的，审核通过后我会在这里留言。
> > P.S. 微软商店过长的审核周期，也是让我想放弃维护商店版的一个重要原因。
> 
> 更新了最最新版试了下可以了！感谢！微软商店更新方便啊~~

商店版有个不好的地方，每次更新都换目录，安全软件规则要重新确认一次，托盘图标也要重新拖下位置。

**Comment by VShawn** [comment]
> 更新了最最新版试了下可以了

感谢测试！

你们速度真快，我都是现在才发现审核通过了，是你们的 store 有更新提醒么？

> 商店版有个不好的地方，每次更新都换目录，安全软件规则要重新确认一次，托盘图标也要重新拖下位置。

安全软件规则我不需要弄，所以不清楚，但我这里 WIN10 21H2 不需要重新拖托盘图标位置呀？

**Comment by leezm** [comment]
> > 更新了最最新版试了下可以了
> 
> 感谢测试！
> 
> 你们速度真快，我都是现在才发现审核通过了，是你们的 store 有更新提醒么？
> 
> > 商店版有个不好的地方，每次更新都换目录，安全软件规则要重新确认一次，托盘图标也要重新拖下位置。
> 
> 安全软件规则我不需要弄，所以不清楚，但我这里 WIN10 21H2 不需要重新拖托盘图标位置呀？

win11要拖一下...我是手动刷新触发更新的...

**Comment by VShawn** [comment]
请问各位，现在的最新版本，这个问题还出现么？或者说出现得还频繁么？

**Comment by yujianjian1013** [comment]
新版本没有出现过问题了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月23日(周二) 下午5:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1Remote/PRemoteM] 0.7版本后第二次打开 RDP 会回报 4360 错误 (Issue #263)




 
请问各位，现在的最新版本，这个问题还出现么？或者说出现得还频繁么？
