### ISSUE TITLE
支持分享导出导入链接

### ISSUE THREAD

**Issue by Kerwin1202** [1Remote/PRemoteM#265]
因为目前一个是因为没有同步，所以多台机器的时候，必须一个个点击复制地址，复制账号，复制密码有点麻烦，（当然也可以复制db，但是会覆盖）
另一个如果想将其中一个分享给其他人，也得一个个复制操作

**Comment by VShawn** [comment]
感谢您的建议，但导入导出链接这个功能我不会去做，因为这个软件目前不会考虑增加服务器端的概念，于是“链接”这个东西就自然无法存在了。

> 必须一个个点击复制地址，复制账号，复制密码有点麻烦

这个操作好像不需要吧，你可以直接导出再导入就可以复制到第二台机器上了

![image](https://user-images.githubusercontent.com/10143738/179342673-004d728a-ae98-4dd5-b8b7-adbcbfec8e24.png)

我个人目前的做法是把 db 放到共享文件夹中共享到几台机器，但有时候会出现文件冲突。

另外其实我之前有考虑过增加一个服务器端用于团队内部共享一些服务器的配置，但由于个人业余生活繁忙，鸽了。
