### ISSUE TITLE
Tasktray stuck after local desk resolution change, 桌面分辨率改变后，托盘右键菜单空白。

### ISSUE THREAD

**Issue by ndd200** [1Remote/PRemoteM#270]
![premotem右键bug](https://user-images.githubusercontent.com/453933/180592024-bda0d6cf-78f4-42de-b519-1e5b0b9e9d52.png)

桌面分辨率改变后，托盘图标右键菜单变透明，并且虚框很难消失，如果强行去选择里面的选项，会弹应用程序未响应。
操作系统Win11，PRemoteM 0.7 Git版。

复现方法如下。
远程桌面上的PRemoteM右键错误：
1.笔记本远程台式机，在台式机上启动PRemoteM。
2.切换下笔记本上的远程桌面窗口，窗口模式（最大化，窗口化），让远程系统的桌面分辨率发生改变。
3.台式机上的PRemoteM托盘右键出错。

本地PRemoteM右键错误：
1.笔记本上启动一个PRemoteM。
2.笔记本接入/拔出外置显示器。
3.笔记本上的PRemoteM托盘右键出错。

怀疑启动PRemoteM后，手动修改下桌面分辨率就能快速复现问题。没试过……

**Comment by VShawn** [comment]
Thanks for the bug report, the bug is fixed and will be published in next patch.
