### ISSUE TITLE
password group

### ISSUE THREAD

**Issue by latzyx** [1Remote/PRemoteM#271]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the enhancement here.

**Comment by latzyx** [comment]
If you want to add the default account password, customize your choice.

**Comment by latzyx** [comment]
Hope to increase the default account password, customize selection, and facilitate use

**Comment by majkinetor** [comment]
Sorry, search before posting new issues as this was already discussed many times.
