### ISSUE TITLE
Enable quick connect Existing instance for clipboard IP. Quick ec2 instance connect

### ISSUE THREAD

**Issue by loverzpark** [1Remote/PRemoteM#273]
**Is your feature request related to a problem? Please describe.**
So Basically if we have an existing machine saved with an IP, we can connect it anytime because we already have the password saved.

Now, In my case what happens is that I use EC2 instances and it gets shut down after my work is done.
The next day When I come and get a new IP address for the same credentials, I need to edit before login everytime with new IP and this became so frustrating because we have shortcuts like `ctrl + M` and have an habit of quick connect.

**Describe the solution you'd like**
Need a way so whenever we are trying to quick connect, give a way to user connect with IP in clipboard without going edit config+save+againreconnect flow.

**Describe alternatives you've considered**
Well, I am not a developer in your technology so can't give a pull request but a high level solution,
If we are quick connecting, if IP in clipboard, show additional hint or link/button in dropdown to connect using clipboard.
Whenever we disconnect, we can ask user if he/she wants to save new IP configuration. 
U can have this flow as your way. just a suggestion if this makes sense, but I think this is a needed feature because its common to have new IP now.

**Additional context**
Aaah, Can't repeate again... but please have a look and make changes ASAP. thanks in advance guys you are awesome as always !!

**Comment by VShawn** [comment]
Thx for the advice.

![image](https://user-images.githubusercontent.com/10143738/181450850-7cb8d6a1-589a-40c7-8d4c-a016fd45a9ce.png)

Actually I have a plan like the picture above for a long time. What stopping me is that I've not found a snappy approach to enter username & password for the `quick connect`.

OTOH, It will break the sessions control logic based on database id if we import `quick connect`.

**Comment by loverzpark** [comment]
I believe we can give an option 
![image](https://user-images.githubusercontent.com/6790861/181844615-efeeb85c-2f64-4954-be6b-dd9f6f32eb5a.png)

Enable this option only in case the clipboard has a valid IP address.

**Comment by majkinetor** [comment]
Sounds awful IMO.

Perhaps better way would be for PRM to popup for missing information. So if you enter password and leave hostname empty you can just ctrl v when you start that connection. This is IMO better as one can also use it for changing username and password.

**Comment by loverzpark** [comment]
Any update on this Guys? What is finalized?

**Comment by VShawn** [comment]
I haven't made my decision yet. 

For now I have to concentrate on turning PRemoteM to 1Remote, new features would not be added.

**Comment by VShawn** [comment]
@loverzpark `quick connect` is basically implemented, see #313
