### ISSUE TITLE
增加一个服务器置顶...

### ISSUE THREAD

**Issue by fkue587** [1Remote/PRemoteM#276]
增加一个服务器置顶...

**Comment by VShawn** [comment]
请问为什么需要置顶呢？

似乎没有多少远程管理工具支持置顶的。

**Comment by fkue587** [comment]
当你管理100个服务器的时候&nbsp;却不能给服务器排序..你就知道多崩溃了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Remote/PRemoteM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月6日(星期六) 上午9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Remote/PRemoteM] 增加一个服务器置顶... (Issue #276)





 
请问为什么需要置顶呢？
 
似乎没有多少远程管理工具支持置顶的。

**Comment by VShawn** [comment]
我不这么认为，我个人管理自己的玩具+公司的工作站约50个服务器。通过合理分组，现在每个标签下也就不到10个服务器。目前没觉得有任何崩溃的点，当然我不是专业网管，不会频繁登录这么多机器。

![image](https://user-images.githubusercontent.com/10143738/183784949-80233f9b-16c2-4692-b8ff-fc5db7ccb048.png)

话说回来本工具开发的初衷，包括现在的目标就是 personal remote manager, 我认为个人使用不会管理到那么多服务器，因此其实一开始开发的时候规划个人版限制了只能管理 20 个服务器，商业版才能管理无限数量的服务器。

当然后来觉得自己太懒，不会去维护商业版，所以就把个人版的服务器数量限制去掉了。
