### ISSUE TITLE
能否支持ctrl+alt+方向键的组合键

### ISSUE THREAD

**Issue by aliciz** [1Remote/PRemoteM#277]
能否支持ctrl+alt+方向键的组合键的功能？

win自带的远程桌面是不支持这种组合键的，JAVA IDEA 开发泪目 :(

微软的microsoft remote desktop (store商店那个）就可以支持，不知道能否加入这个特性

**Comment by VShawn** [comment]
不行的，本项目调用的就是 win自带的远程桌面的封装，所以 win自带的远程桌面 不支持的，本项目也无法支持。

microsoft remote desktop 中有好几个系统自带 mstsc 没有的功能，我怀疑它是魔改过 RDP 客户端。
