### ISSUE TITLE
鼠标中键关闭tab页bug

### ISSUE THREAD

**Issue by zhj9709** [1Remote/PRemoteM#278]
**Describe the bug**
> 公司网络无法上传图片，所以我就直接文字描述了

PRemoteM不使用全屏和mstsc.exe模式式，打开链接后会有一个个tab，我在使用鼠标中键关闭tab页时，我想再次连接网关闭的服务器时，双击无反应。需要过段时间才可以。我测试了以下几种情况：
- 使用鼠标中键关闭tab，短时间内再次双击连接服务器无反应，需要过段时间
- 使用tab页的×关闭tab页，关闭后可以立刻双击再次连接
- 使用软件的×关闭tab页，关闭后可以立刻双击再次连接
- tab页上右键关闭，关闭后可以立刻双击再次连接

**Desktop (please complete the following information):**
 - OS: Win 10 企业版 20H2
 - PRemoteM Version 0.7

**Additional context**

**Comment by VShawn** [comment]
hello, thanks for the bug report. This ticke has been confirmed and fixed.

**Comment by VShawn** [comment]
BUG 原因为将鼠标中键事件绑定到了 tab 控件自身的关闭命令，而其他的关闭方式都是绑定到我自己写的关闭逻辑。
