### ISSUE TITLE
Options for hiding and awaiting termination of the app started before a RDP connection

### ISSUE THREAD

**Issue by bug-ware** [1Remote/PRemoteM#284]
**Is your feature request related to a problem? Please describe.**
I use the start App before (German App vorher starten) connecting to a RDP session. Two things are annoying:
1. A cmd window pops up which doesn't show anything.
2. The RDP connection does not wait.

**Describe the solution you'd like**
Regarding 1) Could you please add an option to start the App in hidden mode? See SW_HIDE, e.g., in ShowWindow function of Windows API.
Regarding 2) Please add an option to wait for the App process to end or alternatively add an option for a delay to be entered and that is waited for before starting the RDP connection.

Hope this make sense. Thanks a lot for developing this App!

goal:
- [x] wait for the script process to end then start the session
- [x] add an option to hide the scrip cmd window

**Comment by VShawn** [comment]
Definitely a BUG it is, I did not design any `cmd window pops up`.

**Comment by VShawn** [comment]
Ohhhh... 

Do you make use of `Before cmd` feature? It may bring us a cmd pop window.

![image](https://user-images.githubusercontent.com/10143738/189050966-fa621a38-ff11-4ebc-b28a-f436919e1e0b.png)

**Comment by bug-ware** [comment]
Yes, exactly; I have the German translation. ;o)

The window doesn't show anything. It is just black. So one could optionally hide it in those cases.

I use this feature to run a script that initiates a ssh connection with tunneling of the rdp port. The "After cmd" script kill this connection afterwards. 
This connection is why I would like the RDP connection to wait until the cmd returns. Otherwise the tunnel is not yet ready. Maybe there is a more elegant solution. Unfortunately, there is no VPN available.

**Comment by VShawn** [comment]
Ok, it make sense, I will firstly try to add a feature to wait script end before it start a RDP session. Then find out how to hide the cmd window.

**Comment by VShawn** [comment]
https://github.com/VShawn/Shawn.Utils/blob/master/Shawn.Utils.Wpf/WinCmdRunner.cs#L44-L63
![image](https://user-images.githubusercontent.com/10143738/189465041-a4e2cd20-79cd-4715-b5a1-1b88886531ce.png)


I found that it has already hide the cmd window in the PRemoteM.

It works on my PC. Maybe some policy on your PC makes it malfunction

**Comment by VShawn** [comment]
[PRemoteM.0.7.1.6.Alpha2-x86-Net6.zip](https://github.com/1Remote/PRemoteM/files/9539856/PRemoteM.0.7.1.6.Alpha2-x86-Net6.zip)

I made this early preview version which will:

1. support run a script file (*.bat|*.ps1|*.py)
2. show cmd window when run the script
3. connection will wait until the cmd returns (until the cmd window close by itself)
4. and yes, int this early preview run script will stuck our UI, this will be fixed in the latter develop for UX improve.

Can you help me test this function?

I will make the feature a better UX if this above achieve our goal :)

**Comment by VShawn** [comment]
[PRemoteM.0.7.1.6.Alpha3-x86-Net6.zip](https://github.com/1Remote/PRemoteM/files/9541817/PRemoteM.0.7.1.6.Alpha3-x86-Net6.zip)

now an option for hide the script window has been added, and the stuck of the main window has been fixed.

I think this ticket is done :)

**Comment by bug-ware** [comment]
Hello.
My script uses some arguments. This was fine before but now gives an error that the file cannot be found. 
I also noticed that one cannot search for "*.cmd" files which are almost equivalent with "*.bat"

**Comment by VShawn** [comment]
Yes, in the old approach, I run a scrip by open cmd.exe then run script in the cmd.exe.

In this approach I can not track the scrip processing procedure, that is to say I don't know when the script process to end. Besides I found that the cmd process sometimes would not be kill after the script run to end in the old approach。

So in this new one, I run the script file directly to achieve the script process tracking. 

Then I usually write arguments in the script files, so I don't consider of the parameters pass...

**Comment by VShawn** [comment]
I make some improvement to make app recognize the parameters.

![image](https://user-images.githubusercontent.com/10143738/189791610-2186b6cc-f1a6-40b4-ab33-cd0a2aec8420.png)

![image](https://user-images.githubusercontent.com/10143738/189791967-b85e788e-d577-4e04-8e77-d6c02b3a875f.png)

[PRemoteM.0.7.1.6.Alpha4-x86-Net6.zip](https://github.com/1Remote/PRemoteM/files/9552982/PRemoteM.0.7.1.6.Alpha4-x86-Net6.zip)

**Comment by bug-ware** [comment]
Thanks. The parameters are recognized now. If I click on "Prüfen" (I guess test or check in English) everything works fine. The script is run and the GUI seems to know if it is finished or not. 
However when I start the RDP connection nothing happens. I.e., it seems that no script is startet. Such, the connection times out with an error. I checked with netstat and found the tunnel port is not opened. Also ssh is not in the task list.
Could you transfer the test routine to the actual connection routine? (Without the MsgBox of course ;o)

**Comment by majkinetor** [comment]
`D:\test - 2.bat -t abc` looks totally funky. 

You probably shouldnt' do that but work with quotes with spaces in names. This is how Explorer handles it with long names:

![image](https://user-images.githubusercontent.com/85767/189984665-3efee73c-4417-4f50-bf38-7bd73f8f152d.png)

![image](https://user-images.githubusercontent.com/85767/189984723-86f30a0f-7852-41c9-8bb9-30faf481a138.png)

**Comment by VShawn** [comment]
@majkinetor 

> D:\test - 2.bat -t abc looks totally funky.

Ahaha, I knew it. This should be "D:\test - 2.bat" in Windows.

But this place can be edit by user, I concerned that someone write something without quotes.

So I add this test case and cheek if the quotes can be add by my code.

![image](https://user-images.githubusercontent.com/10143738/190043211-13fabd3a-5943-4537-bfc5-7f674bfe35e0.png)

Works too:
![image](https://user-images.githubusercontent.com/10143738/190046373-fd2adb17-0e59-41cd-a560-1fe25adeffac.png)


@bug-ware

> However when I start the RDP connection nothing happens. I.e., it seems that no script is startet. Could you transfer the test routine to the actual connection routine?

sure thing :)

[PRemoteM.0.7.1.6.Alpha5-x86-Net6.zip](https://github.com/1Remote/PRemoteM/files/9562186/PRemoteM.0.7.1.6.Alpha5-x86-Net6.zip)

**Comment by bug-ware** [comment]
> sure thing :)

Works like a charm so far!
Thanks a lot! This makes my RDP really remote when working from home ;o)
