### ISSUE TITLE
Add ico suffix to the list of supported file types when importing a logo

### ISSUE THREAD

**Issue by bug-ware** [1Remote/PRemoteM#289]
**Is your feature request related to a problem? Please describe.**
Importing a logo/icon from ico file works although the file select dialog does not list ico files on default.

**Describe the solution you'd like**
Add ico suffix to the list of supported file types.

**Comment by VShawn** [comment]
IMO This format is not easy to use, but I can add the *.ico to supported type.

**Comment by bug-ware** [comment]
Well *.ico is the usual and standard windows icon format. There are several editors which are easy to use. People might have plenty of them, e.g., in mRemoteNG\Icons folder.
Thanks.

**Comment by VShawn** [comment]
Well... for me ico is not easy to edit as bmp or png, so I don't use it if I have any other choice.
