### ISSUE TITLE
Protocol app can't be run from the PATH

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#293]
**Is your enhancement related to a problem? Please describe.**
I have wfreerdp.exe on the PATH. I still have to specify full PATH to it in PRM options.

**Describe the solution you'd like**
If it is on the PATH it should run just by the name. This can be used to integrate it with less config with other tools.

**Additional context**

The chocolatey `bin` folder is on the PATH:

![image](https://user-images.githubusercontent.com/85767/192323079-d38d93db-fe24-46b1-b3dd-26104168fb0d.png)

BTW, since latest release of PRM, wfreerdp is not embedded as connection tab, in previous it was (the same version of wfreerdp).

**Comment by majkinetor** [comment]
Env vars could be supported to for portability reasons.

**Comment by VShawn** [comment]
Reading paths from environment variables was never considered before. 

I make this feature now:

[PRemoteM.0.7.1.7.beta.2-x64.zip](https://github.com/1Remote/PRemoteM/files/9671894/PRemoteM.0.7.1.7.beta.2-x64.zip)

**Comment by majkinetor** [comment]
That doesnt seem to work:

I tried
You implemented usage of env vars, such as: `%ChocolateyInstall%\bin\wfreerdp.exe` and `%FOO%\bar.exe% and in both cases it doesn't work, and doesn't even report exe missing.

Also, since I have `%ChocolateyInstall%\bin` on the `PATH` env. var, it should work without any path.

**Comment by majkinetor** [comment]
Second thing is way more important, as it allows one to install arbitrary protocols and PRM will just be able to work with them:

`cinst premotem vnc winspc wfreerdp ....`

Then Premotem can even come with predefined protocols that will just work if the app is somewhere on the system.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/193165350-fe1d6676-fab5-497c-a388-e7959835beca.png)

![image](https://user-images.githubusercontent.com/10143738/193165390-9634543e-5bf5-41a6-8638-8b56e9995825.png)

![image](https://user-images.githubusercontent.com/10143738/193165514-8708c595-12fd-41eb-bcac-db3295d7341b.png)


IT WORKS ON ME

How your PATH be like?

**Comment by VShawn** [comment]
test the path with `%BlabLA%\bio`

works too

![image](https://user-images.githubusercontent.com/10143738/193184612-632582c3-7da7-44c3-bf08-8e78f6e094a7.png)

**Comment by majkinetor** [comment]
### _Using_ path in `PATH` env var

<details><summary>PATH</summary>

![image](https://user-images.githubusercontent.com/85767/193466623-aff8e196-ba87-42f3-a28b-646b646d292a.png)</details>
<details><summary>wfreerdp</summary> 

![image](https://user-images.githubusercontent.com/85767/193466647-03f618bf-6cf7-48e5-bbbe-b0062174dcc0.png)
</details>

<details><summary>Protocol</summary> 

![image](https://user-images.githubusercontent.com/85767/193466690-b2d34036-0df8-4b19-ad9c-aae52657a65c.png)

</details>

<details><summary>Connection</summary> 

![image](https://user-images.githubusercontent.com/85767/193466756-f78fb096-6457-4d38-9cad-a49a3c89dab3.png)

</details>

<details><summary>Result: popup</summary> :

![image](https://user-images.githubusercontent.com/85767/193466766-fe2db36d-b512-4260-94db-85fd1480f02e.png)

</details>

### Setting path using env var inside it

I also tried to use `ChocolateyInstall` env var inside wfreerdp path:

<details><summary>wfreerdp</summary> 

![image](https://user-images.githubusercontent.com/85767/193466802-3b15c6e2-b0d9-4f8f-9b13-a69ebe5b062e.png)
</details>

<details><summary>Connection</summary> 

![image](https://user-images.githubusercontent.com/85767/193466802-3b15c6e2-b0d9-4f8f-9b13-a69ebe5b062e.png)</details>

<details><summary>Result: black screen</summary> 

![image](https://user-images.githubusercontent.com/85767/193466897-68a31ddc-5db5-43ff-9e0e-0db06261fbcc.png)

</details>

![image](https://user-images.githubusercontent.com/85767/193466923-0b5144ca-1d03-40c3-b01e-fdbe7d364304.png)

**Comment by VShawn** [comment]
Ahh, I tested it on `APP` protocol, not test the runner, let me check the runner path after I back home from vacation.

**Comment by VShawn** [comment]
A bug was found in external runner path checker which make PATH not work. 

[PRemoteM.0.7.1.7.beta.3-x64.zip](https://github.com/1Remote/PRemoteM/files/9771889/PRemoteM.0.7.1.7.beta.3-x64.zip)

**Comment by majkinetor** [comment]
First case now works, second case still doesn't.

And, its still not embedded although option is ticket.

**Comment by VShawn** [comment]
second case is chocolatey case? I don't have a chocolatey installed, maybe test it later.

**Comment by majkinetor** [comment]
No, I just used choco as an example:

For example try `%SystemRoot%\notepad.exe`

**Comment by VShawn** [comment]
Ahhh I see, you means using the environment variable in path directly.

**Comment by majkinetor** [comment]
This will especially be useful in multiuser scneario with relational db holding data.

**Comment by VShawn** [comment]
goal, tested with winscp :)

![image](https://user-images.githubusercontent.com/10143738/195555832-e3333264-91e2-45f2-beda-c08967bd9098.png)

[PRemoteM.0.7.1.7.beta.3-x64.zip](https://github.com/1Remote/PRemoteM/files/9774934/PRemoteM.0.7.1.7.beta.3-x64.zip)

**Comment by majkinetor** [comment]
Works now.

**Comment by VShawn** [comment]
god damn GFW, I can not push to github now.

`
fatal: Could not read from remote repository.
`

**Comment by majkinetor** [comment]
Probably temporary
