### ISSUE TITLE
After update to Win11 22h2 the launcher not recognizes inputs

### ISSUE THREAD

**Issue by stetze88** [1Remote/PRemoteM#294]
**Describe the bug**
After Windows 11 Update to 22h2 the launcher do sporadic not recognizes inputs.
You can tipp anything, nothing shows in the launcher.

![image](https://user-images.githubusercontent.com/73733823/192598017-490e4244-29c8-4f92-8129-efa7c6cf499f.png)

**Desktop (please complete the following information):**
 - OS: Win11 Pro 22h2
 - PRemoteM Version 0.6.2.2 and 0.7.1.5 tested

**Comment by VShawn** [comment]
humm, my win11 in VirtualBox need updates, I test it latter.

**Comment by VShawn** [comment]
can not get 22h2 update...

![image](https://user-images.githubusercontent.com/10143738/192951850-54229b6b-ab58-4650-b690-17ce8f4ac5e1.png)

**Comment by stetze88** [comment]
You must download the [Windows11InstallationAssistant.exe](https://www.microsoft.com/de-de/software-download/windows11?9d47a9e1-e53b-49a1-92ca-a647d62dc410=True): The Feature Update is not yet published to all via Windows Update.
But today my 1Remote works withouth problems. Maybe my notebook has needed a few reboots after upgrade. I think we can close the bug and a will reopen it, if i realize further problems.
