### ISSUE TITLE
Enhancement tag search

### ISSUE THREAD

**Issue by SaltyYuki** [1Remote/PRemoteM#296]
Hello,

**Is your enhancement related to a problem? Please describe.**
When I use tag to search a server I need to write the entire tag name to filter

**Describe the solution you'd like**
exemple I have a tag #linux for some of my servers
When I  search  "#lin" I want PRemotem to start filter any server with a tag who start by #lin 

Thanks for PremoteM btw I use it everyday :D !

**Comment by majkinetor** [comment]
You could click them in Tags tab, they are sorted.

**Comment by Kikilluh** [comment]
I agree with SaltiYuki.  
The big advantage of PRemoteM for me is the quick launcher, it would be more efficient if we could interact with everything related to connections through the launcher rather than opening the client.

However, maybe it would be better to search for `#lin` and, rather than having all the servers with this tag, have the list of tags containing `lin`. Just like server search actually but into the tag view.  And when we click on the chosen tag, all servers with that tag appears.

**Comment by majkinetor** [comment]
> it would be more efficient if we could interact with everything related to connections through the launcher rather than opening the client.

I don't agree. The usecases are different - you use launcher to be quick and use recently used stuff, you use list to scan for stuff, check out all the connections and use additional non everyday features like bulk connect/editing. 

> However, maybe it would be better to search for #lin and, rather than having all the servers with this tag, have the list of tags containing lin

The more natural fit for this is search on Tags tab 

> When I use tag to search a server I need to write the entire tag name to filter

The main problem here seems to be tag input, i.e. there is no autocomplete offered with tag names. If you could type #li<tab> to get all #linux servers, that would be OK, right ?

**Comment by VShawn** [comment]
> When I search "#lin" I want PRemotem to start filter any server with a tag who start by #lin


> The main problem here seems to be tag input, i.e. there is no autocomplete offered with tag names. If you could type #li to get all #linux servers, that would be OK, right ?

basically the autocomplete feature sucks in PRM, I dont know how to make a vscode like autocomplete for PRM for now. So it is not easy to build autocomplete feature here.

We can firstly support `type #lin to list tags who start by #lin`(Although it feels a little weird)

Then try to make the autocomplete tigger by tpyed `#`

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/198168544-656f3fef-a661-400a-af0a-d9cadc965764.png)

goal `type #lin to list tags who start by #lin`
