### ISSUE TITLE
Tag Menu enhancement 

### ISSUE THREAD

**Issue by SaltyYuki** [1Remote/PRemoteM#297]
Hello !

**Is your enhancement related to a problem? Please describe.**
I have too much tag for the current view of tag and I can't view all my tag

**Describe the solution you'd like**
Can you had a search bar and a scrollbar  in this view 

![image](https://user-images.githubusercontent.com/36296195/193052082-d9216386-536a-4701-b0aa-f1419d76b186.png)

Thanks !

**Comment by majkinetor** [comment]
More columns would be nice too. Lot of empty space here.

**Comment by VShawn** [comment]
wow, That's a lot of tags. 

Then we need:

- [ ] tag search
- [ ] more columns

**Comment by VShawn** [comment]
I've make tag list searchable

![image](https://user-images.githubusercontent.com/10143738/197374472-29c029d6-cbfe-446c-af72-3585be8fa004.png)
