### ISSUE TITLE
最大化，可以覆盖任务栏

### ISSUE THREAD

**Issue by livepu** [1Remote/PRemoteM#299]
需要多个远程同时链接，但又想最大化利用屏幕。
如果子窗口的任务栏和主机任务栏一起，很容易误按菜单。

目前我的解决方法是主机任务栏自动隐藏，这样就暂时舒服了。

**Comment by zhj9709** [comment]
我也是隐藏任务栏使用的

**Comment by VShawn** [comment]
最大化覆盖任务栏这个操作很违反Windows的用户习惯哎。

我这边有时候是把服务器的任务栏放在上面，本地任务栏在下面，就不会误触了。

**Comment by VShawn** [comment]
不小心关掉了ticket，我现在的最大化是交给Windows自动控制的，如果要最大化覆盖任务栏就得自己控制窗口的尺寸，实现类似chrome浏览器按F11那样的全屏显示效果。我再想想能不能搞。

**Comment by livepu** [comment]
已经很多程序支持F11全屏的。希望这款支持。

**Comment by livepu** [comment]
测试的版本，这个功能好像不够稳定。只尝试了一次，不知道是否快捷键传递到了rdp系统。
或者改一下这个功能的快捷键方便一点。
