### ISSUE TITLE
German Translation for Ports

### ISSUE THREAD

**Issue by meyomey** [1Remote/PRemoteM#300]
Just one small thing: The translation for ports into German is very funny. In "Häfen" ships sail and anchor. In German, Ports are also called Ports ;-) 
![2022-10-07_07h36_49](https://user-images.githubusercontent.com/33765557/194476348-33ac0bec-864b-4ed2-b009-660e021e6416.png)

**Comment by VShawn** [comment]
thank you for the report. I got `Häfen` from google translate :)
