### ISSUE TITLE
Protocol is not hosted

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#303]
**Describe the bug**
I use freerdp protocol and hosting is ticket. It worked so far, until latest release. Now, hosting window popups up breefly (0.5s) but freerdp is not hosted

**Expected behavior**
It should get hosted the same as before.

**Screenshots**

![image](https://user-images.githubusercontent.com/85767/195533510-28460496-be95-4de7-9afe-da55f34cd669.png)
![image](https://user-images.githubusercontent.com/85767/195533935-29a28598-1bb9-4463-b335-1e0dff2d4437.png)

**Desktop (please complete the following information):**
 - OS: Win10 Enterprise
 - PRemoteM Version 0.7.1.7 beta 3

**Comment by VShawn** [comment]
can you provide the latest version which works fine? Then I can findout different between them.

**Comment by majkinetor** [comment]
All versions up to latest 6 I tried had the same problem. Seems to be something on wfreerdp side ...
