### ISSUE TITLE
Bulk Connect opened with new window instead of opened in new tab

### ISSUE THREAD

**Issue by I-Fun** [1Remote/PRemoteM#314]
**Describe the bug**
Open New Window instead of open in the new tab if we select all and click connect,
it will causing your hardware resource full or freeze

**To Reproduce**
1. Create Multiple Connection & Protocol, in this case i create about 10 connections of RDP
2. Click on Select All / Tick the checkbox on the top left corner
3. Click Connect on the bottom / footer of application
4. The Connection will bursting with new windows and causing your PC Freeze

**Expected behavior**
it supposed to be opened on the new tab instead of new window

**Screenshots**
![3378---06_01-20-18](https://user-images.githubusercontent.com/7077766/200135131-a67f514f-8b5d-4f64-ab48-95f1dea62eba.gif)

**Desktop :**
 - OS: Win10 Pro 21H1 x64
 - PRemoteM Version : 0.7.1.6

**Comment by VShawn** [comment]
bug confirm, I will fix it soon

**Comment by VShawn** [comment]
done!
