### ISSUE TITLE
Shortcut for moving from tab to another tab

### ISSUE THREAD

**Issue by I-Fun** [1Remote/PRemoteM#315]
**Is your feature request related to a problem? Please describe.**
I really need shortcut to moving from tab to tab it'll make the work easier..

**Describe the solution you'd like**
maybe shortcut like SecureCRT had or the internet browser had, like **ctrl+tab** for moving from tab to tab

![3382---07_08-12-43](https://user-images.githubusercontent.com/7077766/200207120-adda6d67-270c-433a-baa7-2492fd5a76c4.gif)
this tab switched when i press **ctrl + tab**

**Comment by VShawn** [comment]
local app cannot capture the shortcut during a rdp session, so we can not make a shortcut tab switch

---

TLTR

https://github.com/1Remote/PRemoteM/issues/40
