### ISSUE TITLE
Some interface quirks

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#316]
1. Combo with names is IMO meaningless <details><summary>details</summary> 
![image](https://user-images.githubusercontent.com/85767/200629508-c4c9934d-f1d3-44f8-9f78-f2726361ac6d.png)</details>
1. When editing connection and you select tag from the combo, you need to double enter (first enter selects it, the next applies it). It should need only 1 as it is not intuitive - I frequently do not get selected tag applied because of this. Its even worst when you use a mouse, u must first click the item but then you must use [+] or enter to apply it. This is meaningless. Since you already selected 1, apply it imediatelly .

**Comment by VShawn** [comment]
> basically the autocomplete feature sucks in PRM, I dont know how to make a vscode like autocomplete for PRM for now. So it is not easy to build autocomplete feature here.

_Originally posted by @VShawn in https://github.com/1Remote/PRemoteM/issues/296#issuecomment-1267870202_


It trobule me for a while.

**Comment by VShawn** [comment]
because of the sucks autocomplete, I have no choose but design selection setp like this.

`tab` `up` `down` key change selection, `enter` key confirm the selection

**Comment by VShawn** [comment]
Maybe i can make it works smoothly, I got idea before  went to sleep last night.

**Comment by majkinetor** [comment]
What about combo with names ? Tags work OK now.

**Comment by VShawn** [comment]
`Combo with names` will leave how it be like now.

It's useful when I add SSH and SFTP sessions with a same address.
