### ISSUE TITLE
Tags in launcher

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#320]
**Is your enhancement related to a problem? Please describe.**
Tags are not visible in launcher but search still looks into them.

**Describe the solution you'd like**
We need tags to be clear here why is item selected 

**Additional context**

![image](https://user-images.githubusercontent.com/85767/201655945-63cd01ac-4059-4f19-b674-ba523170aeab.png)

**Comment by VShawn** [comment]
hum... The added height makes the interface less attractive

**Comment by VShawn** [comment]
I make it be like this, not support very long tag name.

![image](https://user-images.githubusercontent.com/10143738/207823612-f4a891b8-e957-4a9b-8e6d-b5cbd04176d2.png)
