### ISSUE TITLE
Icons for Windows 11, Server 2019 and Server 2022

### ISSUE THREAD

**Issue by Joly0** [1Remote/PRemoteM#322]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Would be great, if icons for Windows 11, Server 2019 and Server 2022 could be added or a template with a small documentation in the wiki on how to create the icons on our own, so one could create them and make a pr

**Describe alternatives you've considered**

**Additional context**

**Comment by majkinetor** [comment]
I agree, icons are still pretty bad. Perhaps it would be good idea to let users just specifiy in configuration custom icon folder and document what icon size looks the best.

**Comment by VShawn** [comment]
Before I fix it, you can use you own icon image by click here:

![image](https://user-images.githubusercontent.com/10143738/207277129-f5640bfd-e9c5-4b89-be6d-f69e9c2d38bf.png)

png 128X128 would be the best.

---

In fact I can't find my Photoshop desige file for Windows logo :(. Then I have to re-create them. Maybe some one can share a SAAS to let us create icons

---

>>> let users just specifiy in configuration custom icon folder

For most people, they will not create their own icons, custom icon folder is meaningless for them.

For the people need custom icon the `select` button is enough for them IMO.

What do you think? @majkinetor

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/207861641-d625149e-c866-42bb-840d-987784f5c714.png)

new icon made by me with paintoolsai
