### ISSUE TITLE
RDP advances combination key issue

### ISSUE THREAD

**Issue by xieyuqiang** [1Remote/PRemoteM#323]
**Is your enhancement related to a problem? Please describe.**
When "combination key" is checked, Win key and Win+Left  will be transported.
When "combination key" is unchecked, Win key and Win+Left  will  not be transported.

**Describe the solution you'd like**
I would like to transport Win key while not to transport Win+Left. There is no ways to do it for now.

**Describe alternatives you've considered**
Addind an new options in Adances for Win key may be better.

**Additional context**
Add any other context or screenshots about the enhancement here.

**Comment by xieyuqiang** [comment]
I also want to transport Win+D while not transporting Win+Left/Right, so that the remote destop is working like a local desktop, and I can switch them using Win+Left/Right.

**Comment by anpicasso** [comment]
If you press CTRL + ALT + HOME while on a full screen RDP session the focus goes back to the local PC, so Win+Left should do what you are trying to do. It certainly is not as seamless as I'd like but you get used to it.

**Comment by VShawn** [comment]
YES, Components provided by Microsoft for RDP not allow us select which combination key to redirect.

Note that a individual key down is always be redirected to remote desk when RDP get focus. In your case there's no way(AFAIK) to not redict `win` key.

My workaround just like how @anpicasso does.
