### ISSUE TITLE
快速切换回真机

### ISSUE THREAD

**Issue by LiXiaYu** [1Remote/PRemoteM#324]
我现在有对远程桌面进行截图的需求，特别是想要截屏鼠标指向某个按钮出现的浮动信息框。如果我把鼠标点击外面的真机，那么可以调用真机的截图软件快捷键，但是远程桌面的浮动信息框已经不再显示了，因为鼠标挪走了。
所以，请问有没有什么好的解决方案呢？

**Comment by VShawn** [comment]
你好，没有办法，微软设计的远程桌面机制就是如此，无法打破。所以很多商业远程桌面软件都是使用自己的远程桌面协议，绕过了微软的。
