### ISSUE TITLE
Add option for icon in the taskbar

### ISSUE THREAD

**Issue by gustaebel** [1Remote/PRemoteM#328]
I like PRemoteM very much ;-)

But one thing that bugs me is that the taskbar icon changes depending on which connection tab is currently open. I understand that a lot of people like this feature, but I struggle regularly to find my PRemoteM window when I have lots of apps open at the same time.

I think it would be a great addition to have a simple option to switch off this behavior, so that the default PRemoteM icon is shown in the taskbar.

Keep up the good work!

**Comment by VShawn** [comment]
I didn't realize that there are someone preferred a fixed icon. 

Since this requirement is easy to implement, I will take it..... Although I don't know how many people need it :)

I will add an option("Show session icon instead of the app icon") to enable / disapble the icon change behavior of our tab window.

**Comment by gustaebel** [comment]
Great, that is exactly what I need!

**Comment by majkinetor** [comment]
Not sure if this works, I now always have [P] icon.

**Comment by majkinetor** [comment]
![image](https://user-images.githubusercontent.com/85767/208920405-453e8099-88b5-4ce7-a854-7a4f2e9eb13b.png)

**Comment by VShawn** [comment]
`Combine taskbar buttons` in your screen shot shows the icon of mainwindow.

Close main window and launch a session by `ctrl` + `m`, you will get current icon.

**Comment by majkinetor** [comment]
Hm, I tried that too, but for some reason now it works... OK, sorry for trouble.

**Comment by majkinetor** [comment]
I tried in sandbox:

![image](https://user-images.githubusercontent.com/85767/208930680-0af89a2f-e537-4e01-b9e9-4aba4d4d3809.png)

**Comment by VShawn** [comment]
> Hm, I tried that too, but for some reason now it works... OK, sorry for trouble. 

it works now？ how you make it work？

**Comment by majkinetor** [comment]
Well, I made sure everything is restarted and there is no main windows on. And it did work, although I suspected this from the start and did it before.... Now I used pristine environment in sandbox and it doesn't work as you can see on the screen. 

So sometimes it works sometimes it doesn't but I am not sure on what it depends.
