### ISSUE TITLE
What about adding support import configuration from .rdp file?

### ISSUE THREAD

**Issue by JamesLewisLiu** [1Remote/PRemoteM#330]
**Is your feature request related to a problem? Please describe.**
The import option only support .prma or mRemoteM's .csv, I use PRemoteM for the first time and found that I cannot import my existing .rdp configuration files.Now I have to open them with notepad and manually copy the configuration into it.

**Describe the solution you'd like**
Support import configuration from .rdp file

**Comment by VShawn** [comment]
technically 

- a .rdp file made by mstsc.exe would not contain any password for the session. 
- a .rdp file with password will keep a password like `password 51:b:01000000D08C9DDF0115D1118C7A00C04FC297EB0100000086FE310FB`, I not sure if we can get plaintext from it.

that mean a session import from .rdf may need user edit twice to fill in the password. IMO it's user un-friendly.

You you have anysolution for this?

**Comment by JamesLewisLiu** [comment]
I have never embed password into the .rdp files, I didn't even know that existed.

In fact I've got used to use password manager like 1Password to input the passwords, I am afraid that I can't give you some advices.

**Comment by majkinetor** [comment]
Windows keeps those passwords in the Credential store, and youc an access that. I doubt its worth the trouble tbh.

**Comment by VShawn** [comment]
> We already kinda have an export (you named it Preview RDP file)

I even have an incomplete .rdp file importer in my utility :), just didn't solve the password import.

**Comment by majkinetor** [comment]
Its not that important, you can always enter password by hand. But its easily done.

You could import them if you want by identified by `TERMSRV\<computer_address_or_name>`:

![image](https://user-images.githubusercontent.com/85767/209107652-dcf5a68c-0d83-4800-b7c2-b4382f7ea6e2.png)

**Comment by VShawn** [comment]
Hmm...New knowledge reception.

I didn't know Credential Manager before. Can I get plaintext from Credential Manager?

> You can also provide an option for PRM to save password there in addition to its internal database 

I'll consider of this. Sounds amazing.

**Comment by majkinetor** [comment]
>  Can I get plaintext from Credential Manager?

User that created them can, they are encrypted with his SAM identity. Another user can't. Which is OK in this case.

I tried that now but ....  I can get some passwords but not all. Not those created from the mstsc becasue it returns empty password:

![image](https://user-images.githubusercontent.com/85767/209145345-9b905334-1adc-4037-b272-ef9289335adf.png)

You can edit it via Credential Management UI but password is hidden (I can try to unhide dots but I guess they are here just cosmetics):

![image](https://user-images.githubusercontent.com/85767/209145493-f7a13b40-3df4-4464-8fa6-8057aa031440.png)

Other passwords can be converted using for example `ConvertFrom-SecureString -SecureString $cred.Password -AsPlainText`

So this can be done, but not sure if there is an API for all situations, but it certainly can be hacked as this popular tool shows:
* https://www.nirsoft.net/utils/credentials_file_view.html

I think its a lot of work for now, it can be added later if people want it.

**Comment by majkinetor** [comment]
BTW, maybe this is specific to my own system, on some systems there is _Show_ button in Credential Manager next to the password and then it is displayed.
