### ISSUE TITLE
Please update about setup to build

### ISSUE THREAD

**Issue by itagagaki** [1Remote/PRemoteM#331]
First, I used VS2019 according to the documentation. However, an error revealed that the solution assumes VS2022.
So I changed to using VS2022. But I still get some errors. For example, CS0723 on line 20 of DataServiceTests.cs.

**Comment by VShawn** [comment]
ahh, yse we need the latest VS2022 to build it since port to .net6.

THX for the remind.



You need this two workload:

![image](https://user-images.githubusercontent.com/10143738/209246928-9b42b7d0-ecdb-491f-bf56-3f2c9341fad2.png)
