### ISSUE TITLE
软件切换到PremoteM时，任务栏输入法图标消失

### ISSUE THREAD

**Issue by zhj9709** [1Remote/PRemoteM#332]
每次打开PremoteM时，任务栏的输入法图标消失，点击一下任务栏后，输入法图标又出现了。当win11任务栏对齐方式设置为居中，而且打开的软件较多时，再切换到其他软件时，等输入法图标出现后，任务栏上居中的软件图标都要向左移动。

https://user-images.githubusercontent.com/13991774/209626121-119bebd7-8db4-4ea0-ae1a-4df142240190.mp4

**Comment by VShawn** [comment]
这个APP没有任何代码是用于控制系统IME的，因此改这个项目的代码也无法修复你遇到的问题的。

我怀疑你是遇到了win11的某种bug，否则无法解释输入法为何会消失。一般最多是从中文输入法切换到了英文输入法，而不是整个输入法图标没了。

**Comment by zhj9709** [comment]
> 这个APP没有任何代码是用于控制系统IME的，因此改这个项目的代码也无法修复你遇到的问题的。
> 
> 我怀疑你是遇到了win11的某种bug，否则无法解释输入法为何会消失。一般最多是从中文输入法切换到了英文输入法，而不是整个输入法图标没了。

win10也有这样的问题，skype会议演示的时候也有这样的问题，感觉还会有其他软件有同样的问题，可以想办法避免这种情况吗

**Comment by VShawn** [comment]
因为问题产生的原因都不明确，所以目前没有解决方案。

我怀疑可能与任务栏的图标合并有关系，因为我的设置是从不合并，因此从来没有遇到过输入法消失的问题。

![image](https://user-images.githubusercontent.com/10143738/210509670-9d705590-28c1-4c3b-bc06-c6d7194fdac2.png)

**Comment by VShawn** [comment]
这个似乎是 Windows 的 feature. 我用系统自带的 MSTSC 打开远程桌面，也出现了本地输入法状态栏消失的现象。

![1](https://user-images.githubusercontent.com/10143738/210512584-c34a4325-7016-46b3-a5c7-9cc5a0081b73.gif)
