### ISSUE TITLE
请问如何编译.net 48版本的

### ISSUE THREAD

**Issue by cweijan** [1Remote/PRemoteM#333]
老哥你好, 请问releases中的.net48版本是如何编译? 我下载了源码, 在vs中只能编译.net60的.

.net60版本在普通windows机上需要额外安装一个运行时才可运行, 而.net48版本不需要, 更加方便, 可以告知下吗.

**Comment by VShawn** [comment]
https://github.com/1Remote/PRemoteM/blob/1Remote_dev/Ui/Ui.csproj#L14-L17

修改此处即可。

**Comment by cweijan** [comment]
谢谢
