### ISSUE TITLE
Inactive SSH windows do not update until new data comes.

### ISSUE THREAD

**Issue by ryny24** [1Remote/PRemoteM#334]
PRemoteM is amazing!  I love it, I just have one weird issue. I have many SSH tabs open that monitor LOG files. But when data comes in for a tab that is not active, it's screen is not updated. When I switch to it, I notice the timestamps are old. If I wait, the entire screen updates only after new log data is written (sometimes is often), or if I press ENTER. But to have to press a key on each window really slows down the monitoring of my systems.

Is this normal or do I have an option wrong?

 - PRemoteM Version 0.7.2

**Comment by VShawn** [comment]
I think it maybe a bug of inactive KiTTY, I'm not very sure bug our SSH is based of KiTTY, all PRemoteM do is open a new session of KiTTY and set it's size and position. It seems KiTTY do not update the terminal when it’s in the background in your case.

**Comment by ryny24** [comment]
Ok, thanks for the info. I will try and see if there is a way to fix KiTTY.

**Comment by VShawn** [comment]
I find it that KiTTY will not update terminal when it's minimized. Just like we switch to another tab and leave KiTTY in background with PRemoteM.
