### ISSUE TITLE
能不能增加使用RDP的时候关于Alt+Tab的选项

### ISSUE THREAD

**Issue by Allen-Sven** [1Remote/PRemoteM#335]
我需要频繁在远程计算机以及本地计算机切换，能不能增加一个选项在使用RDP时，Alt+Tab可以在本地计算机的软件中切换，而不是直接发送快捷指令到远程计算机。

**Comment by VShawn** [comment]
很遗憾，受限于微软的RDP控件，无法实现这一点。
