### ISSUE TITLE
可否用参数直接打开某个Session

### ISSUE THREAD

**Issue by NottMee** [1Remote/PRemoteM#336]
比如我已经配置了一个远程连接NAS
使用类似参数PRemoteM.exe -NAS直接打开

没有在Wiki里找到相关的参数列表
最后感谢这么好的软件

**Comment by VShawn** [comment]
你好，感谢你的建议。

但之前我们有过类似的讨论：https://github.com/1Remote/PRemoteM/issues/188

意思是允许创建快捷方式，快捷方式中使用参数PRemoteM.exe -NAS，实现双击快捷方式来打开一个新会话。

但Windows store版本要实现这个功能太过于麻烦，因此为统一exe版本和store版本的功能，就把这个方案给否了。
