### ISSUE TITLE
在右下角托盘鼠标点击右键退出时报错

### ISSUE THREAD

**Issue by shijunzhang** [1Remote/PRemoteM#337]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.InvalidOperationException: 关闭窗口后，无法设置可见性，也无法调用 Show、ShowDialogor 或 WindowInteropHelper.EnsureHandle。
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at Stylet.WindowManager.ShowWindow(Object viewModel, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at PRM.View.MainWindowViewModel.<>c__DisplayClass43_0.<ShowMe>b__1() in D:\a\PRemoteM\PRemoteM\Ui\View\MainWindowViewModel.cs:line 261
   at Stylet.Execute.OnUIThread(Action action)
   at PRM.View.MainWindowViewModel.ShowMe(Boolean isForceActivate, Nullable`1 goPage) in D:\a\PRemoteM\PRemoteM\Ui\View\MainWindowViewModel.cs:line 259
   at PRM.Service.TaskTrayService.TaskTrayIconOnMouseDoubleClick(Object sender, MouseEventArgs e) in D:\a\PRemoteM\PRemoteM\Ui\Service\TaskTrayService.cs:line 53
   at System.Windows.Forms.NotifyIcon.OnMouseDoubleClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Private.CoreLib.dll
----------------------------------------
PRemoteM
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
PresentationFramework
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/PresentationFramework.dll
----------------------------------------
WindowsBase
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/WindowsBase.dll
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.dll
----------------------------------------
System.Xaml
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/System.Xaml.dll
----------------------------------------
System.IO.Packaging
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/System.IO.Packaging.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Private.Uri.dll
----------------------------------------
PresentationCore
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/PresentationCore.dll
----------------------------------------
DirectWriteForwarder
    程序集版本:6.0.2.0
    Win32 版本:6,0,822,36807 @Commit: 7a75fd34f53bc300206bd8cfc636527934dd17af
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/DirectWriteForwarder.dll
----------------------------------------
System.Runtime.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.InteropServices.dll
----------------------------------------
System.Runtime.CompilerServices.VisualC
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.CompilerServices.VisualC.dll
----------------------------------------
System.Diagnostics.Debug
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Diagnostics.Debug.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Threading.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.Registry
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/Microsoft.Win32.Registry.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Collections.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Collections.Specialized.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.ComponentModel.Primitives.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Threading.Thread.dll
----------------------------------------
System.Configuration.ConfigurationManager
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Diagnostics.Process
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Diagnostics.Process.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Memory.dll
----------------------------------------
System.Xml.ReaderWriter
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Linq.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Threading.ThreadPool.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Diagnostics.TraceSource.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Windows.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/System.Windows.Extensions.dll
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.ComponentModel.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Collections.Concurrent.dll
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.ObjectModel.dll
----------------------------------------
Stylet
    程序集版本:1.3.6.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.Requests
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.WebHeaderCollection.dll
----------------------------------------
Shawn.Utils.Wpf
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Drawing.Primitives.dll
----------------------------------------
Shawn.Utils
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/System.Windows.Forms.Primitives.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.IO.Pipes
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.IO.Pipes.dll
----------------------------------------
System.Security.AccessControl
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Security.AccessControl.dll
----------------------------------------
Shawn.Utils.WpfResources
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Security.Principal.Windows
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Security.Principal.Windows.dll
----------------------------------------
UIAutomationTypes
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/UIAutomationTypes.dll
----------------------------------------
Markdig.Wpf
    程序集版本:0.5.0.1
    Win32 版本:不可用
    代码库:
----------------------------------------
ICSharpCode.AvalonEdit
    程序集版本:6.1.3.50
    Win32 版本:不可用
    代码库:
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/netstandard.dll
----------------------------------------
System.IO.FileSystem.AccessControl
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.IO.FileSystem.AccessControl.dll
----------------------------------------
System.Security.Claims
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Security.Claims.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Linq.Expressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.Numerics.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Data.Common.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Reflection.Primitives.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Private.CoreLib.dll
----------------------------------------
VariableKeywordMatcher
    程序集版本:1.0.10.0
    Win32 版本:不可用
    代码库:
----------------------------------------
VariableKeywordMatcher.I
    程序集版本:1.0.10.0
    Win32 版本:不可用
    代码库:
----------------------------------------
VariableKeywordMatcherIn1
    程序集版本:1.0.11.0
    Win32 版本:不可用
    代码库:
----------------------------------------
VariableKeywordMatcher.Provider.ChineseZhCnPinYinInitials
    程序集版本:1.0.10.0
    Win32 版本:不可用
    代码库:
----------------------------------------
VariableKeywordMatcher.Provider.ChineseZhCnPinYin
    程序集版本:1.0.10.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.IO.MemoryMappedFiles.dll
----------------------------------------
System.IO.Compression
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.IO.Compression.dll
----------------------------------------
System.Console
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Console.dll
----------------------------------------
JsonKnownTypes
    程序集版本:0.5.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Dragablz
    程序集版本:0.0.3.234
    Win32 版本:不可用
    代码库:
----------------------------------------
AxMSTSCLib
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
MSTSCLib
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/mscorlib.dll
----------------------------------------
System.Data.SQLite
    程序集版本:1.0.115.5
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Transactions.Local
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Transactions.Local.dll
----------------------------------------
System.Diagnostics.Tracing
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Diagnostics.Tracing.dll
----------------------------------------
Dapper
    程序集版本:2.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.RegularExpressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Text.RegularExpressions.dll
----------------------------------------
System.Xml.XDocument
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Xml.XDocument.dll
----------------------------------------
System.Private.Xml.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Private.Xml.Linq.dll
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/System.Drawing.Common.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Runtime.Loader.dll
----------------------------------------
PresentationFramework.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/zh-Hans/PresentationFramework.resources.dll
----------------------------------------
UIAutomationProvider
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/UIAutomationProvider.dll
----------------------------------------
PresentationFramework.Aero2
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/PresentationFramework.Aero2.dll
----------------------------------------
System.Windows.Controls.Ribbon
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/System.Windows.Controls.Ribbon.dll
----------------------------------------
WindowsFormsIntegration
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/WindowsFormsIntegration.dll
----------------------------------------
Markdig
    程序集版本:0.22.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
PresentationUI
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/PresentationUI.dll
----------------------------------------
PresentationCore.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/zh-Hans/PresentationCore.resources.dll
----------------------------------------
PresentationUI.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/zh-Hans/PresentationUI.resources.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Xml.Linq.dll
----------------------------------------
PresentationFramework-SystemXml
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework-SystemData
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36807
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/PresentationFramework-SystemData.dll
----------------------------------------
System.Net.Http
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.Http.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Net.Sockets
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.NameResolution.dll
----------------------------------------
VirtualizingWrapPanel
    程序集版本:1.5.7.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Security.Cryptography.Encoding
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.822.36804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.822.36804
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.8/Accessibility.dll
----------------------------------------
System.Net.Quic
    程序集版本:6.0.0.0
    Win32 版本:6.0.822.36306
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.8/System.Net.Quic.dll
----------------------------------------

************** JIT 调试 **************

**Comment by VShawn** [comment]
感谢反馈，看日志像是鼠标点退出按键的时候主窗口关闭了，但鼠标同时触发了双击打开窗口，由于此时主窗口已关闭，但又要求打开主窗口，就发生了异常。

加一个判断就行了。
