### ISSUE TITLE
How to pass in the configuration parameters of RDP

### ISSUE THREAD

**Issue by jinzhi666** [1Remote/PRemoteM#341]
How to pass in the configuration parameters of RDP? 
For example: turn off the background of the remote desktop, turn off the sound of the remote desktop, speed up the access speed, etc.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/211989299-321f2e77-9bb4-4fbb-861d-9cb87d2325ff.png)

You can simply set performance to low to fit you access speed.


and sound:

![image](https://user-images.githubusercontent.com/10143738/211989574-92dcc780-a444-4864-9481-151316fe9d95.png)
