### ISSUE TITLE
Make updates easier

### ISSUE THREAD

**Issue by MWinhard** [1Remote/PRemoteM#345]
**Is your feature request related to a problem? Please describe.**
Each time a new version is released, I have to go to github, find the list of changes, download the zip file, exit PRmoteM, extract the zip file to the folder where PRemoteM is installed. This can be done easier.

**Describe the solution you'd like**
Display all releases newer than the installed one in the PRemoteM main window. The release text may be fetched from github. Beside each release offer a button [Install this release].

If you cannot create files in the install folder, disable the button and give it a tooltip that says why it's disabled.

**Describe alternatives you've considered**
A checkbox "Install updates automatically". But: As PRemoteM is mostly used by admins and developers, the [Install this release] button is a better fit, IMHO.

**Additional context**
When I click the [Install this release] button, every step necessary should be automated. After the update is installed, restart PRemoteM.

PRemoteM.exe can be renamed while running. So you don't need a separate updater EXE. Just rename the old EXE, copy the new EXE, start the new EXE, then exit the old EXE. Same procedure should work for dll files.

**Comment by majkinetor** [comment]
Your suggestion is IMO out of domain for this type of software. No app should reivnent package managers.

**Comment by VShawn** [comment]
Agrees.. since you can get update from `Microsoft store` or `Chocolatey`, we have no need to deploy a update service for this app.

I desiged the update system in the very begining, and cancel the plan after `Microsoft store` version was published :)

**Comment by MWinhard** [comment]
I see your point. But...

I like to have my programs portable. So I did with PRemoteM. Whenever I have to set up a new physical or virtual machine I can just copy the folder with all my portable programs. The copy includes all my settings and customizations.

Let's be honest. Installing software on a new machine is done in a snap. What takes time is restoring all the settings of each program. Even if there's an export/import machanism.

With chocolatey or winget i just get the software. No settings at all.

**Comment by majkinetor** [comment]
Whats wrong with install via choco/winget, copy your db to that folder (or entire folder). You can also do that other way around, choco will just update what you already have there, just put it in the folder where it was originaly placed by the package manager.

I use it in portable manner in this way.

**Comment by MWinhard** [comment]
You asked what's wrong with choco/winget: Afterwards you have to somehow copy your settings over. This is a different process for every piece of software. Way more work than just copy one folder with all your portable programs and their setting.

But anyway. I'll give it a choice.

I tried winget. It ignores the location parameter. Just installs in default location. Not what I need. Uninstalled.

I installed chocolatey the default way. Then moved the whole directory from C:\ProgramData\Chocolatey to F:\PORTABLE\Chocolatey. Updated the machine environment variable ChocolateyInstall=F:\PORTABLE\Chocolatey.
Run Powershell as admin and install PRemoteM: `choco install premotem --force`

Now it's installed in C:\tools\PRemoteM. Not what I expected. How do I tell it that it has to install in F:\PORTABLE\PRemoteM?

**Comment by majkinetor** [comment]
Oh, details details... you are just piling them up :)

winget uses windows store in this case, its the same as you GUI clicked on it, you don't have a choice of folder there too.

OK, go this way:


2. Install chocolatey
3. `choco install premotem --params '/InstallDir:F:\Portable\PRemotem'`  (if you have spaces in path put folder in the quotes
1. Copy your PRM folder to `F:\Portable\PRemoteM`, overwrite all.

Now you can update with `cup premotem` or `cup all` if you have more pacakges.

**Comment by MWinhard** [comment]
Now it works. And it's still completely portable. :-)

Thank you very much!

**Comment by majkinetor** [comment]
You are welcome :)
