### ISSUE TITLE
Plus in connection windows does nothing

### ISSUE THREAD

**Issue by Gameniti** [1Remote/PRemoteM#351]
**Describe the bug**
When you have an active connection you have the tab list on top. There is a little + which seems to indicate that you can do something with it but you can't.

**To Reproduce**
1. Connect to anything
2. See top next to the connection
3. Click on +

**Expected behavior**
Either do something (tbh I have no idea what is planned for this) or disable if there is no function.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/26071510/216741918-21f85534-b615-4f83-8672-a17b30d3d73b.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 22H2
 - PRemoteM Version 0.7.2

**Comment by VShawn** [comment]
On mine it will pop the launcher, not work for you?

**Comment by VShawn** [comment]
Ahhh I see, plus does nothing when launcher is disabled. It's indeed a bug.

**Comment by VShawn** [comment]
I will remove the button when launcher is disabled.
