### ISSUE TITLE
Customizable Title Buttons for connection view

### ISSUE THREAD

**Issue by VShawn** [1Remote/PRemoteM#353]
It can't be implemented the way you want. Its not a good UX. 

It could eventually be implemented as 

1. an config option that would be by default disabled ( [ ] Connecton title doubleclick triggers reconnecting ). I still dont like it, totally arbitrary feature creep.
2. another button in the titlebar, also as an option, disabled by default ( [o] Show reconnect button in the connection title bar )
![image](https://user-images.githubusercontent.com/85767/215768865-81736fed-d656-45ca-b3f7-db210f47599d.png)

I think second option makes sense, since right clicking shows _close_ and _reconnect_ as options. Since you can close with middle click, you technically do not need x button (so it could be an option too).

So I think that we could have "Connection button options"

~3. [ ] Edit button?~
1. [x] Reconnect button
2. [x] Close button

and we can keep the context menu having all of the options always.

This would allow us to have some other buttons in the future evetnually, if the need arise (_edit_ for example, could be very useful for adding Markdown Notes as requested on another ticket).  This would let one have anything one wants, even no buttons at all.

_Originally posted by @majkinetor in https://github.com/1Remote/PRemoteM/issues/344#issuecomment-1410324186_

**Comment by VShawn** [comment]
done :)

![image](https://user-images.githubusercontent.com/10143738/216756193-e8d7d2f8-d7e7-4b21-93ac-4bb55d41902b.png)

**Comment by majkinetor** [comment]
Look great :)
