### ISSUE TITLE
Note field in connection configuration

### ISSUE THREAD

**Issue by profbaco** [1Remote/PRemoteM#78]
There is a possibility to create a NOTE field for each connection. This would make it easier, because then we could describe - in short text - what each service has on each server.
This observation would only be available in the LIST view, as shown in the image below. 

===================================

Existe a possibilidade de se criar um campo de OBSERVAÇÃO para cada conexão. Isto facilitaria, pois aí poderíamos descrever - em texto curto - o que cada serviço tem em cada servidor.
Esta obseravação, só estaria disponível na visualização por LISTA, conforme imagem abaixo.

![Exemplo](https://user-images.githubusercontent.com/5287317/107041985-f30b5800-679f-11eb-988c-b0aa58b1805c.gif)

**Comment by majkinetor** [comment]
Yeah, its always good to have comment/description/note field for any entity anywhere.

In that regard, the thing that needs to get worked on is UX, among other things:

- How much text is allowed ?
- Multiline ?
- Markup or plain text ?
- How to present it in the list ?
- Is it searchable ?
- How to not make big empty space for people that will not use it (probably requires option to select visible columns)

**Comment by VShawn** [comment]
Ahhhh, I write note in name field myself.

IMO there was no space for note display, especially in the launcher. and if this note shown only in the listview, it doesn't make much significance.

**Comment by profbaco** [comment]
The point is that, as you can see in my print, I have several servers, and each one has one or more functions in it.
An example is a Job Server (it has other tools that I use and it would be good to have an idea of the main processes that run on it), with this in the name of the station it would be ServerJob and in the description I would put in more detail what this server is responsible for.
I thought of a field with a maximum of 255 characters, even simpler.
The reason for being on the list, is that in this mode, you can put more options, something that the Card would not have. As it is up to each one to choose their visualization, then the person decides whether to use the list or the card. 

=================================

A questão é que, como podem ver no meu print, tenho vários servidores, e cada um tem uma ou várias funções no mesmo. 
Um exemplo é um Servidor de Job (nele tem outras ferramentas que utilizo e seria bom ter uma ideia dos processos principais que rodam nele), com isto no nome da estação seria ServerJob e na descrição colocaria com mais detalhes do que este servidor é responsável.
Pensei em um campo de no máximo 255 caracteres mesmo, coisa mais simples.
O motivo de estar no list, é que neste modo, pode-se colocar mais opções, coisa que no Card não teria como. Como fica a cargo de cada um escolher a sua visualização, então a pessoa decide se quer utilizar o list ou o card.

**Comment by majkinetor** [comment]
> IMO there was no space for note display, especially in the launcher. 

I propose the following. 

Adding a separate viewer of launcher with an easy option to hide it if you want. It shouldn't show if note is empty anyway, but if you do and you don't like it here there is a close button and option to show notes any time:

![image](https://user-images.githubusercontent.com/85767/107117876-8f575c80-687d-11eb-8551-c467ab22c94e.png)

In list view I propose this one, that could also affect search:

![image](https://user-images.githubusercontent.com/85767/107117789-fb859080-687c-11eb-974d-e48eaa81d49b.png)

Edit button could be added here directly but its the shortcut for changing this in configuration.

**Comment by VShawn** [comment]
@profbaco 
> The point is that, as you can see in my print, I have several servers, and each one has one or more functions in it.

we dont know how many people need this note, and how many of them will turely read this note. So I think it is not a good time to implement it. 

for myself, maybe I will never take a glimpse on note: I have several db service, several app server. I will named them in short name by keyword(like `AX DB` `UT3 DB` `Card Web`... ) to remind me what they are using for. (short name is easy for launcher search too)


@majkinetor 
> Adding a separate viewer of launcher with an easy option to hide it if you want.

your approach I think is 
- not beautfuy enought, (in fact I really hope a designer can help redesign the full set of UI)
- will slow down the launch if we read the note.
- markdown... 

BTW I can still read your server info on your screenshot



---

Anyway I think it‘s not the right time for this note, we can planning this when more people want this feature.

**Comment by majkinetor** [comment]
> will slow down the launch if we read the note.

OK, having a note on launcher is definitely overkill.

On full list it seems OK, even if it is shown only in the connection configuration .

> markdown

What's wrong with markdown, but OK, maybe overkill :)

> BTW I can still read your server info on your screenshot

Yeah, I was aware of that, but couldn't be bothered after the fact :)

**Comment by majkinetor** [comment]
@VShawn can we for start add Note/Comment field only in common configuration? It is useful even if not shown on other places?

For example like this:

![image](https://user-images.githubusercontent.com/85767/149663562-31c7ff5b-adbe-4f61-a413-ceb2962eaaa4.png)

**Comment by VShawn** [comment]
I suggest text note only, it's easy to implement.
I don‘t want to handle the rich text format.

**Comment by majkinetor** [comment]
Sure.

**Comment by Kerwin1202** [comment]
+1

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/166623114-0ed86972-34f8-4e29-a25c-97f7a29da1f9.png)

little progress of the note field. I made it markdown supported. And it generate another topic for how to display markdown note on the list view of our main window.

**Comment by majkinetor** [comment]
Thats amazing. Thanks for reconsidering markdown.

**Comment by VShawn** [comment]
I made the note display just as @profbaco's wish

![1](https://user-images.githubusercontent.com/10143738/167517473-9293072e-8a74-4114-a4fe-753a25db8041.gif)

**Comment by majkinetor** [comment]
Maybe to tidy up note interface a bit:

1. Hovering over note icon to display it, instead of clicking it.
3. Add preview button in config editor (or something equivalent, maybe even a hotkey)
4. Its not obvious that markdown is supported. Add a placeholder when note is empty with text like '_Insert markdown notes here_'

5. Context menu looks strange <details><summary>details</summary> 
![image](https://user-images.githubusercontent.com/85767/168417099-cea116a8-26ad-4451-88a4-18822cb6e508.png)
</details>
 
1. Maybe allow editing a note from the display window <details><summary>details</summary> 
![image](https://user-images.githubusercontent.com/85767/168417408-89c2d456-fb61-4781-929a-965adeb78e09.png)
</details>

3. Provide an option to show note when item is selected in launcher, without any clicking (point of launcher is to use it with keyboard only, so clicking a note doesn't seem great). Instead of PRM config, I would add it as a toggle button in a search field <details><summary>details</summary>
![image](https://user-images.githubusercontent.com/85767/168417256-ab238f60-c426-43e3-92f1-a77863a24ddb.png)
</details>

**Comment by VShawn** [comment]
> Provide an option to show note when item is selected in launcher, without any clicking (point of launcher is to use it with keyboard only, so clicking a note doesn't seem great). Instead of PRM config, I would add it as a toggle button in a search field

about this. I think I added a shortcut '←' key to show or hide note. Not very sure if this shortcut is enable in the 0.7alpha. Can't test this I outdoor without a computer. I took iPhone with me only.

Besides I don't how to make a tooltip to let user know this '←' key

advice welcome

**Comment by majkinetor** [comment]
> I think I added a shortcut '←' key to show or hide note.

Lol, yeah you did. Very discoverable :) It actually behaves the same as I want.  

> advice welcome

Advice is to provide a toggle button like I described :) With a tooltip that says "Show note on selection (hotkey: ←)".

**Comment by majkinetor** [comment]
Note hints have invalid Markdown :)


![image](https://user-images.githubusercontent.com/85767/170026502-c499b6c0-526c-4327-98fc-891b2771a305.png)

It would look like this when rendered:

## Markdown support
    - foo
    - bar


It should be like this:

```
# Markdown support

- foo
- bar
```

Note that although some engines tolerate no new line between header and next thing, many do not.

Also, inconsistent behavior on note preview icon. You should make it show on hover too, as with connection list :)

Maybe you think this is overly pedantic, but little things is what distinguish great tools from the junk ones.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/177744040-91823f5f-20ca-423d-8d72-bb6bc5c60fd6.png)

I've fix this, I missed this ticket earlier some how
